#!/bin/bash 
if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi

#source config
######################################
ext=.mp4

abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
exit 0
  fi
  stream_video () {
  	#sed -e 's/^.*\(title=[^ ,]*\).*$/\1/'

wget -qO - $agent "$server1"|grep iframe|sed 's/ /_/g;s/"/ /g'|sed -e 's/^.*\(\/\/[^ ,]*\).*$/\1/'|sed "s/'/ /g"|awk '{print "http:"$1}'> $HOME/.tvmaxe-cli/.tmp/mirrors
mirrors=`cat $HOME/.tvmaxe-cli/.tmp/mirrors|sed 's/\// /g'|awk '{print $2}'|nl`

  	
$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Surse disponibile" --clear \
         	 --menu ":::" 30 50 30 $mirrors  2> $tempfile
      		selectie0=$?
		abandon
  		
  	$DIALOG --infobox "Procesez..." 5 15
		mirrors_nr=`cat $tempfile`
		
		upload=`cat $HOME/.tvmaxe-cli/.tmp/mirrors|sed -n "${mirrors_nr}p"`
	$DIALOG --infobox "Procesez... /n $upload" 5 50
		subtitrare=`wget -qO - $upload|grep srt|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
  }
}
functie_seriale () {

		wget -qO - "$adresa_serial"  $agent |grep seriale2|grep position:relative|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $7,"http://www.990.ro/"$4}' >$HOME/.tvmaxe-cli/.tmp/epizoade_serial

		epizoade2=`cat $HOME/.tvmaxe-cli/.tmp/epizoade_serial|sed "s/&#039;/'/g"|awk '{print $1,"off"}'|nl`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Epizoade $nume_serial" --clear \
         	 --checklist ":::" 80 50 80 $epizoade2  2> $tempfile
      		selectie0=$?
      		nr_linie=`cat $tempfile|sed 's/"//g'`
			nr_alese=`echo $tempfile|wc -w`
		abandon
		
		
$DIALOG --infobox "Procesez..." 5 15
functie_seriale_2 () {

		adresa_epizod=`cat $HOME/.tvmaxe-cli/.tmp/epizoade_serial|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		#server1=`wget -qO - $adresa_epizod $agent|grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa_epizod|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`

		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		nume=`cat $HOME/.tvmaxe-cli/.tmp/epizoade_serial|awk -v var="$nr_linie_colectie" '{print var,$1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_linie_colectie}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		stream_video
}

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume1" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati"  \
	"03" "Descarcare" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

 	case "$selectat" in
	01)	 
		for nr_linie_colectie in  $nr_linie 
		do
		functie_seriale_2
		$DIALOG --title "$nume_serial" \
				--backtitle "tvmaxe-cli" \
				--yesno "Doriti redarea epizodului $nume1 ?"  7 60
						raspuns=$?
					case "$raspuns" in
		0)
		#subtitrare
		
		$DIALOG --infobox "$nume1" 10 60
		#subtitrare
		$DIALOG --infobox "Adresa Film: \n$upload " 10 80
		
		
		#$player2 $film1  -sub $subtitrare1 -sub $subtitrare2 &>/dev/null
		youtube-dl $upload -o -|player2 sub $subtitrare - &>/dev/null
		
		;;
  		 1) exit 0 
		;;
   		255) exit 0 
		;;
					esac
		
		done
		
		exit 0
	;;

	02)	
mkdir -p $salvare/$nume_serial
		for nr_linie_colectie in  $nr_linie 
		do

		functie_seriale_2

		#subtitrare

		#wget -O $salvare/$nume_serial/$nume1.srt  $subtitrare1 || wget -O $salvare/$nume1.srt $subtitrare2 &>/dev/null 
		#wget -bqc -O $salvare/$nume_serial/$nume1$ext $film1 
wget -O $salvare/$nume_serial/$nume1.srt $subtitrare

youtube-dl $upload -o $salvare/$nume_serial/$nume1$ext &>/dev/null &

echo -e "\e[93m\e[42m Numele fisierului video difera in timpul descarcarii de numele subtitrarii \e[0m"

		sleep $delay ; 
	$player2 $salvare/$nume_serial/$nume1$ext.part &>/dev/null
	
		done
		exit 0
	;;

	
03) 
mkdir -p $salvare/$nume_serial
		for nr_linie_colectie in  $nr_linie 
		do

		functie_seriale_2

	

wget -O $salvare/$nume_serial/$nume1.srt $subtitrare
youtube-dl $upload -o $salvare/$nume_serial/$nume1$ext 
		
	
		done
		exit 0
;;
	esac
}


meniufilm () {
$DIALOG --infobox "Procesez...$nume1" 5 15

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcatti" \
	"04" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 10 60
		#subtitrare
		$DIALOG --infobox "Adresa Film: \n$upload " 10 80
		
		youtube-dl $upload -o -|$player2 -sub $subtitrare - &>/dev/null
		#$player2 $film1  -sub $subtitrare1 -sub $subtitrare2 &>/dev/null
		
		
		exit 0
;;

	02)	
		$DIALOG --infobox "Adresa Film: \n$upload " 10 80
		
		wget -O $salvare/$nume1.srt $subtitrare
		youtube-dl $upload -o $salvare/$nume1$ext &>/dev/null &
	echo -e "\e[93m\e[42m Numele fisierului video difera in timpul descarcarii de numele subtitrarii \e[0m"
		sleep $delay
		$player2 $salvare/$nume1$ext.part  &>/dev/null
		
		exit 0
;;
	03)

	$DIALOG --infobox "Adresa Film: \n$upload " 10 80
		 
		wget -O $salvare/$nume1.srt $subtitrare
		youtube-dl $upload -o $salvare/$nume1$ext  
		
		
		exit 0
;;
	04)	exit 0 ;;
  esac

 }

	$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme 990.ro" --clear \
          --menu ":::" 25 30 25 \
	"01" "Filme noi" \
	"02" "Episoade noi FSub" \
	"03" "Episoade noi Sub" \
	"04" "Seriale dupa gen" \
	"05" "Calitate +" \
	"06" "Filme dupa gen" \
	"07" "Cautare film" \
	"08" "Parasiti"  2>$tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`
case "$selectat" in

	01) #filme noi
	$DIALOG --infobox "Procesez..." 5 15

	 wget -qO - http://www.990.ro $agent|sed -n "/Ultimele filme/,/Filme calitate/ p"|grep link|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $5,$4}'|grep "filme-">$HOME/.tvmaxe-cli/.tmp/noi

		filmenoi=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed "s/&#039;/'/g"|awk '{print $1,"|"}'`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $filmenoi  2> $tempfile
      		selectie0=$?
		abandon
		$DIALOG --infobox "Procesez..." 5 15
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_nou}p"`
		#server1=`wget -qO - www.990.ro/$adresa $agent |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa|grep smastervidcom | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume= `cat $tempfile` 
		#nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`cat $tempfile|sed 's/[\/ ]/_/g'`
		#subtitrare
		
		
		
		meniufilm
;;
02) #Episoade Fsub
$DIALOG --infobox "Procesez..." 5 15
wget -qO - http://www.990.ro $agent |sed -n "/Ultimele episoade/,/cu subtitra/ p"|grep link|sed -e "s/ /_/g;s/^.*\(href[^ ,]*\).*$/\1/;s/[<>']/ /g"|awk '{print $3,$2}'>$HOME/.tvmaxe-cli/.tmp/noi

		episoade_noi=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed "s/&#039;/'/g"|awk '{print $1}'|nl`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $episoade_noi  2> $tempfile
      		selectie0=$?
		abandon
		
		nr_film_nou=`cat $tempfile`
		adresa_serial=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_nou}p"`



		#server1=`wget -qO - www.990.ro/$adresa_serial $agent|grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa_serial|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		meniufilm 
		;;

03) #Episoade Sub
$DIALOG --infobox "Procesez..." 5 15
wget -qO - http://www.990.ro $agent |sed -n "/cu subtitra/,/Ultimele filme/ p"|grep link|sed -e "s/ /_/g;s/^.*\(href[^ ,]*\).*$/\1/;s/[<>']/ /g"|awk '{print $3,$2}'>$HOME/.tvmaxe-cli/.tmp/noi

		episoade_noi=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed "s/&#039;/'/g"|awk '{print $1}'|nl`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $episoade_noi  2> $tempfile
      		selectie0=$?
		abandon
		
		nr_film_nou=`cat $tempfile`
		adresa_serial=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_nou}p"`



		#server1=`wget -qO - www.990.ro/$adresa_serial $agent |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa_serial|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`

		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		meniufilm 
		;;

04) #seriale
$DIALOG --infobox "Procesez..." 5 15
#Seriale dupa gen

  $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Seriale dupa gen |" --clear \
          --menu ":::" 25 30 25 \
"01" "Toate" \
"02" "Actiune" \
"03" "Animatie" \
"04" "Aventura"  \
"05" "Comedie" \
"06" "Crima" \
"07" "Documentar" \
"08" "Dragoste" \
"09" "Drama" \
"10" "Fantezie" \
"11" "Horror" \
"12" "Istorie" \
"13" "Mister" \
"14" "Razboi" \
"15" "Thriller" \
"16" "SF" \
"17" "Sport" \
"18" "Western" 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`

  
  case "$selectat" in
01)		gen_serial= ;;
02) 	gen_serial=actiune;;
03)		gen_serial=animatie;;	 
04)		gen_serial=aventura;;
05)		gen_serial=comedie;;
06)		gen_serial=crima;;
07)		gen_serial=documentar;;
08)		gen_serial=dragoste;;
09)		gen_serial=drama;;
10)		gen_serial=fantezie;;
11)		gen_serial=horror;;
12)		gen_serial=istorie;;
13)		gen_serial=mister;;
14)		gen_serial=razboi;;
15)		gen_serial=thriller;;
16)		gen_serial=gen=SF;;
17)		gen_serial=sport;;
18)		gen_serial=western;;
	esac
 
#################3
$DIALOG --infobox "Procesez..." 5 15

if [ ! -f $HOME/.tvmaxe-cli/.tmp/seriale_pagini ]
	then

pagini_seriale=`wget -qO - "http://www.990.ro/seriale.php?afisare=grid&gen=$gen_serial&data=&order=ci&pagina=1"$agent |grep "numarpagini"|sed '$d'|sed 's/<[^>]*>/ /g;s/[A-Za-z]*//g;s/[&;]//g'|awk '{print $NF}'`

$DIALOG --infobox "Am gasit $pagini_seriale pagini. Incep paginarea lor" 5 50
sleep 2
i=1
		for p in `seq 1 $pagini_seriale` ; do
			wget -qO - "http://www.990.ro/seriale.php?afisare=grid&gen=$gen_serial&data=&order=ci&pagina=$(( i++ ))" $agent| sed -n "/numarpagini/,/numarpagini/ p"|grep link|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $7,"http://www.990.ro/"$2}'>>$HOME/.tvmaxe-cli/.tmp/seriale_pagini
		$DIALOG --infobox "Pagini $(( i++ ))/$pagini_seriale" 5 15;sleep 0.5
		done
	fi
$DIALOG --infobox "Procesez..." 5 15

		
		seriale2=`cat $HOME/.tvmaxe-cli/.tmp/seriale_pagini|sed "s/&#039;/'/g"|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Seriale $gen_serial" --clear \
         	 --menu ":::" 30 50 30 $seriale2  2> $tempfile
      		selectie0=$?
		abandon
	
		nume_serial=`cat $tempfile`
		nr_serial=`cat $HOME/.tvmaxe-cli/.tmp/seriale_pagini|sed -n "/$nume_serial/="`
		
		adresa_serial=`cat $HOME/.tvmaxe-cli/.tmp/seriale_pagini|awk '{print $2}'|sed -n "${nr_serial}p"`


$DIALOG --infobox "Procesez..." 5 15

functie_seriale
;;
04)

		$DIALOG --infobox "Procesez..." 5 15
		wget -qO - http://www.990.ro $agent |sed -n "/Filme calitate/,/tabberAutomatic/ p"|grep link|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $5,$4}'>$HOME/.tvmaxe-cli/.tmp/noi

		episoade_noi=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1,"|"}'`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $episoade_noi  2> $tempfile
      		selectie0=$?
		abandon
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_nou}p"`
		#server1=`wget -qO - www.990.ro/$adresa $agent |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		meniufilm
		;;


05) #calitate +

$DIALOG --infobox "Procesez..." 5 15

	 wget -qO - http://www.990.ro $agent|sed -n "/Filme calitate/,/tabberAutomatic/ p"|grep link|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $5,$4}'|grep "filme-">$HOME/.tvmaxe-cli/.tmp/noi

		filmenoi=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1,"|"}'`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Calitate +" --clear \
         	 --menu ":::" 30 50 30 $filmenoi  2> $tempfile
      		selectie0=$?
		abandon
		$DIALOG --infobox "Procesez..." 5 15
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/noi|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_nou}p"`
		#server1=`wget -qO - www.990.ro/$adresa $agent |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		
		meniufilm;;
06) #Filme dupa gen
			$DIALOG --infobox "Procesez..." 5 15

			 $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Seriale dupa gen |" --clear \
          --menu ":::" 25 30 25 \
"01" "Toate" \
"02" "Actiune" \
"03" "Animatie" \
"04" "Aventura"  \
"05" "Comedie" \
"06" "Crima" \
"07" "Documentar" \
"08" "Dragoste" \
"09" "Drama" \
"10" "Fantezie" \
"11" "Horror" \
"12" "Istorie" \
"13" "Mister" \
"14" "Razboi" \
"15" "Thriller" \
"16" "SF" \
"17" "Sport" \
"18" "Western" 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`

  
  case "$selectat" in
01)		gen_film= ;;
02) 	gen_film=actiune;;
03)		gen_film=animatie;;	 
04)		gen_film=aventura;;
05)		gen_film=comedie;;
06)		gen_film=crima;;
07)		gen_film=documentar;;
08)		gen_film=dragoste;;
09)		gen_film=drama;;
10)		gen_film=fantezie;;
11)		gen_film=horror;;
12)		gen_film=istorie;;
13)		gen_film=mister;;
14)		gen_film=razboi;;
15)		gen_film=thriller;;
16)		gen_film=gen=SF;;
17)		gen_film=sport;;
18)		gen_film=western;;
	esac
 
#################
$DIALOG --infobox "Procesez..." 5 15

	pagini_gen=`wget -qO - "http://www.990.ro/toate-filmele.php?afisare=grid&gen=$gen_film&data=&order=ci&pagina=1" $agent|grep "numarpagini"|sed '$d'|sed 's/<[^>]*>/ /g;s/[A-Za-z]*//g;s/[&;]//g'|awk '{print $NF}'`
	$DIALOG --infobox "Am gasit $pagini_gen pagini. Incep paginarea lor" 5 50		
sleep 2
		i=1
		for p in `seq 1 $pagini_gen` ; do
			wget -qO - "http://www.990.ro/toate-filmele.php?afisare=grid&gen=$gen_film&data=&order=ci&pagina=$(( i++ ))" $agent|sed -n "/numarpagini/,/numarpagini/ p"|grep link|sed "s/ /_/g;s/[<>']/ /g"|awk '{print $7,"http://www.990.ro/"$2}'>>$HOME/.tvmaxe-cli/.tmp/filme_gen
		$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done
		filme_gen=`cat $HOME/.tvmaxe-cli/.tmp/filme_gen|awk '{print $1}'|nl`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "$nume_gen" --clear \
         	 	--menu ":::" 30 70 30 $filme_gen 2> $tempfile
      		selectie0=$?
		abandon
		nr_film_gen1=`cat $tempfile`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/filme_gen|awk '{print "http://www.990.ro/"$2}'|sed -n "${nr_film_gen1}p"`
		#server1=`wget -qO - $adresa $agent |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`

		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video
		nume=`cat $HOME/.tvmaxe-cli/.tmp/filme_gen|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_gen1}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		meniufilm
;;
07) 
 $DIALOG --title "Cauta film:" \
		--backtitle "tvmaxe-cli" \
		--inputbox "Ce film cautati?" 10 35  2>$tempfile
			selectie0=$?
			abandon
			film_cautat=`cat $tempfile`

	$DIALOG --infobox "Caut filmul..." 5 35
			wget --post-data="kw=$film_cautat" $agent http://www.990.ro/functions/search3/live_search_using_jquery_ajax/search.php -qO -|sed "s/href/\n/g;s/ /_/g;s/['<>]/ /g"|sed '1,2d'|awk '{print $18,$2,"990"}'>$HOME/.tvmaxe-cli/.tmp/filme_gasite1

			cat $HOME/.tvmaxe-cli/.tmp/filme_gasite1|sed 's/ /||/g'|sort -d|sed 's/||/ /g' > $HOME/.tvmaxe-cli/.tmp/filme_gasite

film_gasit=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print $1,$3}'`

if [[ -z `cat $HOME/.tvmaxe-cli/.tmp/filme_gasite` ]]; then
$DIALOG	--title 'Eroare' \
	--infobox '\n Nu am gasit filmul cautat' 5 35;sleep 2

exit 0
else



		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Rezultatul cautarii:" --clear \
         	 	--menu  ":::" 30 70 50 $film_gasit 2> $tempfile
      		selectie0=$?
		abandon
		nume_film_gasit=`cat $tempfile`
		nume1=`echo $nume_film_gasit`
		nume_serial=`echo $nume_film_gasit`
		nr_film_gasit=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|sed -n "/$nume_film_gasit/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print "http://990.ro/"$2}'|sed -n "${nr_film_gasit}p"`
		gasit_pe=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print $3}'|sed -n "${nr_film_gasit}p"`

		sursa=`echo $gasit_pe|sed 's/_/ /g'|awk '{print $NF}'`

	if [[ "$sursa" = "990" ]];then
		selectie=`echo $adresa|sed 's/[-\/]/ /g'|awk '{print $3}'`
		if [[ "$selectie" = "filme" ]]; then

		#server1=`wget -qO - $adresa $agent|grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		player_film=`wget -qO - $agent $adresa|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`

		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`

		stream_video

		meniufilm
		
		elif [[ "$selectie" = "seriale" ]]; then
		adresa_serial=$adresa
		player_film=`wget -qO - $agent $adresa|grep mastervid | sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		server1=`wget -qO - $player_film $agent|grep mastervid|sed "s/ /_/g;s/'/ /g;s/http/ http/g"|awk '{print $4}'`
		
		functie_seriale
		#stream_video

		fi

		

	fi
fi
;;
08) exit 0;;
esac


exit 0