#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
play=`echo $player|awk '{print $1}'`
$DIALOG --backtitle "tvmaxe-cli" \
	--title "| youtube/divertisment |" \
	--msgbox "\nInchide bucla de redare" 10 30
	killall $play
	killall youtube &>/dev/null
	killall divertisment &>/dev/null
	exit 0
