#! /bin/bash
source config

######################################
commit1=`wget -qO - https://github.com/calvarr/tvmaxe-cli/commits/master|grep 'class="sha"'|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}'`
commit2=`cat $HOME/.tvmaxe-cli/.commit_tv`

if [[ "$commit1" != "$commit2" ]]; then 
 wget -qO - https://github.com/calvarr/tvmaxe-cli/commits/master|grep 'class="sha"'|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}' > $HOME/.tvmaxe-cli/.commit_tv
wget -qO - https://github.com/calvarr/tvmaxe-cli/commits/master|sed -n  "/commit-title/,/commit-meta/ p"|sed -n '2p'|sed 's/<[^>]*>/ /g' >> $HOME/.tvmaxe-cli/mesaj_actualizare
mesaj=`cat $HOME/.tvmaxe-cli/mesaj_actualizare|sed -n '$p'`

wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/scriptUP > scriptUP

$DIALOG --title "tvmaxe-cli" \
	--infobox "Actualizare noua... \ncommit: $commit1 \n$mesaj" 30 50
sleep 5
fi
######################################
$DIALOG --backtitle "tvmaxe-cli" \
        --checklist ":::" 30 50 30 \
	"01" "Actualizare liste tv" "off"\
	"02" "Actualizare liste radio" "off"\
	"03" "Actualizare tvmaxe-cli" "off" 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
selectat=`cat $tempfile`
nr_optiuni=`cat $tempfile|wc -w`
echo nr_optiuni $nr_optiuni
for p in `seq 1 $nr_optiuni` ; do
optiune=`echo $selectat|awk -v opt=$p '{print "0"opt}'`

		case "$optiune" in
	01)	
		./tvlist
		;;
	02)
		./radiolist
		;;
	03)	./scriptUP
		exit 0;;

esac
done
	exit 0

