#! /bin/bash
$DIALOG --backtitle "tvmaxe-cli" \
        --checklist ":::" 30 50 30 \
	"01" "Actualizare liste_tv" "off"\
	"02" "Actualizare tvmaxe-cli" "off"\
	"03" "Verifica actualizare" "off" 2> $tempfile
      	selectie0=$?
	abandon
selectat=`cat $tempfile`

		case "$selectat" in
	01)	./tvlist
		exit 0;;
	02)	./scriptUP
		exit 0;;
	03)	echo "lucrez inca la asta"
esac
	

