#! /bin/bash


if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
######################################

abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]
	then
   
exit 0
fi
}
	
functie_desene_1 () {
			$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume_film_nou" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Descarcati" \
	"03" "Abandon" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

 	case "$selectat" in
	01)	 
		for nr_linie_colectie in  $nr_linie 
		do
		adresa_epizod=`cat $HOME/.tvmaxe-cli/.tmp/adresa_desen_multiplu|sed -n "${nr_linie_colectie}p"`
		$DIALOG --title "$nume_film_nou" \
				--backtitle "tvmaxe-cli" \
				--yesno "Doriti redarea Epizodului: $nr_linie_colectie $nume_film_nou ?"  7 60
						raspuns=$?
					case "$raspuns" in
		0)
		
		
		
		$DIALOG --infobox "Adresa Film: \n$adresa_epizod " 10 80
		
		youtube-dl "$adresa_epizod" -o - | $player - 
		$postplay
		killall youtube-dl

		;;
  		 1) exit 0 
		;;
   		255) exit 0 
		;;
					esac
		
		done
		
		exit 0
	;;

	02)	
mkdir -p $salvare/$nume_serial
		for nr_linie_colectie in  $nr_linie 
		do

		adresa_epizod=`cat $HOME/.tvmaxe-cli/.tmp/adresa_desen_multiplu|sed -n "${nr_linie_colectie}p"`
		youtube-dl $adresa_epizod -o "$salvare/$nume_film_nou/$nr_linie_colectie_$nume_film_nou.mp4"
		
		done
	;;

	03)	

		exit 0
	;;


	esac
		
}
	$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Desene Animate" --clear \
          --menu ":::" 25 30 25 \
	"01" "Aparitii recente" \
	"02" "clasificare" \
	"03" "Cautare..." \
	"04" "Parasiti"  2> $tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`
case "$selectat" in

	01) #desene noi
	$DIALOG --infobox "Procesez..." 5 15

	 wget -qO - http://deseneledublate.blogspot.ro/|sed -n "/'posts'/,/'hierarchy'/ p"|sed "s/ /_/g;s/['<>]/ /g"|awk '{print $4,$3}'|sed '1d'>$HOME/.tvmaxe-cli/.tmp/desene_noi

	 desene_recente=`cat $HOME/.tvmaxe-cli/.tmp/desene_noi|awk '{print $1,"|"}'`
		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $desene_recente  2> $tempfile
      		selectie0=$?
		abandon
		$DIALOG --infobox "Procesez..." 5 15
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/desene_noi|sed -n "/$nume_film_nou/="`
		adresa_desen=`cat $HOME/.tvmaxe-cli/.tmp/desene_noi|awk '{print $2}'|sed -n "${nr_film_nou}p"`
		wget -qO - $adresa_desen|grep ok.ru|sed 's/ /_/g;s/"/ /g;s/^.*\(http:\/\/ok.ru[^ ,]*\).*$/\1/;s/videoembed/video/'>$HOME/.tvmaxe-cli/.tmp/adresa_desen_multiplu

epizoade=`cat $HOME/.tvmaxe-cli/.tmp/adresa_desen_multiplu|awk '{print $1,"off"}'|nl`


$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Epizoade $nume_film_nou" --clear \
         	 --checklist ":::" 80 50 80 $epizoade 2> $tempfile
      		selectie0=$?
      		nr_linie=`cat $tempfile`
			nr_alese=`echo $tempfile|wc -w`
		abandon
		
		
$DIALOG --infobox "Procesez..." 5 15

		#adresa_epizod=`cat $HOME/.tvmaxe-cli/.tmp/adresa_desen_multiplu|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`

functie_desene_1
;;
02);;
###################################
####################################
03)

$DIALOG --title "Cauta desen:" \
		--backtitle "tvmaxe-cli" \
		--inputbox "Ce desen cautati?" 10 35  2>$tempfile
			selectie0=$?
			abandon
			desen_cautat=`cat $tempfile`

	$DIALOG --infobox "Caut desenul..." 5 35
			wget -qO - http://deseneledublate.blogspot.ro/search?q="$desen_cautat"|sed -n "/'posts'/,/'hierarchy'/ p"|sed "s/ /_/g;s/['<>]/ /g"|awk '{print $4,$3}'|sed '1d'>$HOME/.tvmaxe-cli/.tmp/desene_gasite

			wget -qO - http://deseneledublate.blogspot.ro/search?q=batman|sed -n "/post-title entry-title/,/readmorecontent/ p"
wget -qO - http://deseneledublate.blogspot.ro/search?q=batman|sed ':a;N;$!ba;s/\n/ /g'>batman.txt

			#cat $HOME/.tvmaxe-cli/.tmp/desene_gasite|sed 's/ /||/g'|sort -d|sed 's/||/ /g' > $HOME/.tvmaxe-cli/.tmp/desene_gasite_abc

film_gasit=`cat $HOME/.tvmaxe-cli/.tmp/desene_gasite|awk '{print $1}'`

#if [[ -z `cat $HOME/.tvmaxe-cli/.tmp/desene_gasite` ]]; then
#$DIALOG	--title 'Eroare' \
#	--infobox '\n Nu am gasit desenul cautat' 5 35;sleep 2

#exit 0
#else



		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Rezultatul cautarii:" --clear \
         	 	--menu  ":::" 30 70 50 $desene_gasite 2> $tempfile
      		selectie0=$?
		abandon
		nume_desen_gasit=`cat $tempfile`
		nume_film_nou=`echo $nume_desen_gasit`
		
		nr_desen_gasit=`cat $HOME/.tvmaxe-cli/.tmp/desene_gasite_abc|sed -n "/$nume_desen_gasit/="`
		adresa_epizod=`cat $HOME/.tvmaxe-cli/.tmp/desene_gasite_abc|awk '{print $2}'|sed -n "${nr_desen_gasit}p"`
	
	functie_desene_1	

#fi
;;
04) exit 0 ;;
	
esac
exit 0