#!/bin/bash 
# riprtmp.sh
#http://seperohacker.blogspot.ro/2012/09/how-to-download-hulu-videos-on-linux.html
$DIALOG --title "capstream" \
--backtitle "tvmaxe-cli" \
--inputbox "url web_tv:" 20 50 2>$tempfile
url=`cat $tempfile`
$DIALOG --infobox  "necesar un web_browser capabil sa redea flash \nomor procesele flash existente" 5 35 
	sleep 2
flash=`ps aux | grep flash|sed -n '1p'|awk '{print $2}'`
kill $flash
> $HOME/.tvmaxe-cli/.tmp/rtmptemp

$DIALOG --infobox  "deschid portul tcp 1935 pentru a redirectiona fluxul flash\nnecesara parola\napasati ENTER dupa ce icepe redarea web_tv" 10 40
sleep 1
sudo iptables -t nat -A OUTPUT -p tcp --dport 1935 -j REDIRECT
#sudo iptables -t nat -F
xdg-open $url &>/dev/null
sleep 1
exec 2> /dev/null # Comment out this line if having problems.
rtmpsrv | grep "rtmpdump" | tee $HOME/.tvmaxe-cli/.tmp/rtmptemp &
read i

$DIALOG --infobox  "inchid portul tcp 1935" 5 35
sleep 3
killall rtmpsrv
sudo iptables -t nat -D OUTPUT -p tcp --dport 1935 -j REDIRECT
sleep 3
adr=`cat $HOME/.tvmaxe-cli/.tmp/rtmptemp|sed 's/-r/\n/;s/-o/\n/'|sed -n '2p'`
seek=`cat $HOME/.tvmaxe-cli/.tmp/rtmptemp|sed 's/-o/-o \n/'|sed -n '2p'`
nume_tv=`echo $seek|sed 's/\./ /'|awk '{print $1}'`
rm $seek
$DIALOG --infobox "$adr" 30 50
sleep 3
if [[ ! -s $HOME/.tvmaxe-cli/.tmp/rtmptemp ]];then
$DIALOG --infobox "nu am putut capta adresa" 5 35
sleep 3
else
echo $nume_tv $adr >> $HOME/.tvmaxe-cli/playlist/web_tv.tv
$DIALOG --infobox "Am adaugat adresa la favorite\nNB! unele web_tv captate au timp limitat de functionare" 5 35
sleep 3
fi
