#!/bin/bash -x

source config
######################################

abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
exit 0
  fi
}

subtitrare () {
		key=`echo $upload|sed 's/[\/.html]/ /g'| awk '{print $NF}'`
		subtitrare1=`echo http://superweb.rol.ro/video/jw6/$key.srt`
	}

meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu ":::" 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcati" \
	"04" "Adaugati la favorite" \
	"05" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	
	$DIALOG --infobox "$nume1" 10 60
		subtitrare
		$DIALOG --infobox "Adresa Film: \n$film1 \n\nAdresa Subtitrare: \n$subtitrare1" 10 80
		echo $film1
		$player $film1  -sub $subtitrare1 &>/dev/null
		$postplay
		exit 0 

;;

	02)	wget -O $salvare/$nume1$ext $film1 &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay  &>/dev/null
		killall wget 
		exit 0
;;

	03)	axel -o $salvare/$nume1$ext $film1 2>&1 |grep "%]"| sed -u -e "s,\.,,g;s/\]//" | awk '{printf("\b\b\b\b%4s", $2)}' 2>&1
			echo -ne "\b\b\b\b" #|$DIALOG --gauge "Descarc.." 6 50 10
		exit 0
;;

	04)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;


	05)	exit 0 ;;
  esac

 }

 $DIALOG --title "Cauta film:" \
		--backtitle "tvmaxe-cli" \
		--inputbox "Ce film cautati?" 10 35  2>$tempfile
			selectie0=$?
			abandon
			film_cautat=`cat $tempfile`

	$DIALOG --infobox "Caut pe: www.990.ro" 5 35
			wget --post-data="kw=$film_cautat" --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" http://www.990.ro/functions/search3/live_search_using_jquery_ajax/search.php -qO -|sed "s/href/\n/g;s/ /_/g;s/['<>]/ /g"|sed '1,2d'|awk '{print $18,$2,"990"}'>$HOME/.tvmaxe-cli/.tmp/filme_gasite1
########################################################

	$DIALOG --infobox "Caut pe: www.cinemaxx.ro" 5 35
			wget -qO - http://www.cinemaxx.ro/search.php?keywords="$film_cautat"|sed -n '/biglist/,/footerwrapper/ p'> $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_list

			grep -i '"title">' $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_list |sed 's/ /_/g;s/[<>]/ /g'|awk '{print $2}'> $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_title

			grep -i 'href' $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_list |sed 's/ /_/g;s/"/ /g'|awk '{print $2,"cinemaxx"}' > $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_href

			paste $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_title $HOME/.tvmaxe-cli/.tmp/filme_cinemaxx_search_href| column -s $'\t' -t  >> $HOME/.tvmaxe-cli/.tmp/filme_gasite1

	
cat $HOME/.tvmaxe-cli/.tmp/filme_gasite1|sed 's/ /||/g'|sort -d|sed 's/||/ /g' > $HOME/.tvmaxe-cli/.tmp/filme_gasite

film_gasit=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print $1,$3}'`

if [[ -z `cat $HOME/.tvmaxe-cli/.tmp/filme_gasite` ]]; then
$DIALOG	--title 'Eroare' \
	--infobox '\n Nu am gasit filmul cautat' 5 35;sleep 2

exit 0
else



		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Rezultatul cautarii:" --clear \
         	 	--menu  ":::" 30 70 50 $film_gasit 2> $tempfile
      		selectie0=$?
		abandon
		nume_film_gasit=`cat $tempfile`
		nume1=`echo $nume_film_gasit`
		nume_serial=`echo $nume_film_gasit`
		nr_film_gasit=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|sed -n "/$nume_film_gasit/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print $2}'|sed -n "${nr_film_gasit}p"`
		gasit_pe=`cat $HOME/.tvmaxe-cli/.tmp/filme_gasite|awk '{print $3}'|sed -n "${nr_film_gasit}p"`

fi
#filtru film/serial 990
		sursa=`echo $gasit_pe|sed 's/_/ /g'|awk '{print $NF}'`

	if [[ "$sursa" = "990" ]];then
		

			server1=`wget -qO - www.990.ro/$adresa --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		upload=`wget -qO - $server1 --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep superweb|sed "s/'//g;s/http/ http/g;s/[<>]/ /g"|awk '{print $4}'`
		film1=`wget -qO - $upload --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep "'file': '"|sed '1p'|sed "s/ /_/;s/'/ /g"|awk '{print $3}'|sed '$d'`
		
		

	elif [[ "$sursa" = "cinemaxx" ]];then

	embed=`wget -qO - $adresa|grep pm-embed-code|sed -e 's/^.*\(src=.*\).*$/\1/;s/"/ /g'|awk '{print $2}'`

	server_film1=`wget -qO - $embed|grep mail.ru &>/dev/null 2>&1`
		if [ $? = 0 ]
			then 
			videoapi=`wget -qO - $embed|grep videoapi|sed 's/"/ /g'|awk '{print $3}'`
			film1=`wget -qO - $videoapi|grep r.mail|sed 's/"/ /g'|awk '{print $3}'`

		else
			
			film1=`wget -qO - $embed|grep videomega|sed 's/ /_/g;s/["&]/ /g'|sed -e 's/^.*\(http:\/\/videomega[^ ,]*\).*$/\1/'`
	
		fi
	

	fi
sleep 3




meniufilm

exit 0
