#! /bin/bash
source config
ext=.mp4
		abandon () {
		if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
			exit 0
 		fi
 					}

 		despre_film () {
			$DIALOG --infobox "Procesez..." 5 15
			$DIALOG --infobox "$descriere" 30 50 ; sleep 5


						}

filtru_film () {

	server_film1=`wget -qO - $embed|grep mail.ru &>/dev/null 2>&1`
		if [ $? = 0 ]
			then 
			videoapi=`wget -qO - $embed|grep videoapi|sed 's/"/ /g'|awk '{print $3}'`
			rmail=`wget -qO - $videoapi|grep r.mail|sed 's/"/ /g'|awk '{print $3}'`



			#json=`wget -qO - $rmail|grep requestURL|grep requestURL|sed 's/"/ /g'|awk '{print $3}'`
			#cookie=`wget --save-cookies $HOME/.tvmaxe-cli/.tmp/cookies.txt -qO - $json|sed 's/ /|/g;s/url/\n/g;s/"/ /g'|sed -n '$'p|awk '{print $2}'|sed 's/%2F/\//g;s/%3A/\:/g'`
			#film1=`wget -qO - $json|sed 's/ /|/g;s/url/\n/g;s/"/ /g'|sed -n '$'p|awk '{print $2}'|sed 's/%2F/\//g;s/%3A/\:/g'`
#cookies1=`echo "-cookies -cookies-file $HOME/.tvmaxe-cli/.tmp/cookies.txt"`
#cookies2=`echo "--cookies=on --keep-session-cookies --load-cookies=$HOME/.tvmaxe-cli/.tmp/cookies.txt"`
		
		else
			#cookies1=""
			#cookies2=""
			upload=`wget -qO - $embed|grep vk|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`

			wget -qO - $upload|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse

			film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')
		fi

}



meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	#"03" "Descarcati" \
	"03" "Adaugati la favorite" \
	"04" "Reveniti" \
	"05" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 5 30
#$DIALOG --infobox "$film1 \n\n cookies $HOME/.tvmaxe-cli/.tmp/cookies.txt" 10 60
		#$player $cookies1 "$film1"  &>/dev/null
		youtube-dl --max-quality FORMAT $rmail -o - | $player -
		killall youtube-dl
		exit 0
;;

	02)	
$DIALOG --infobox "$film1" 10 60
#$DIALOG --infobox "$film1 \n\n cookies $HOME/.tvmaxe-cli/.tmp/cookies.txt" 10 60
		#wget -O $salvare/$nume1$ext  $cookies2 "$film1" &>/dev/null &
		youtube-dl --max-quality FORMAT $adr_yt -o $salvare/$nume$ext &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay  &>/dev/null
		killall wget 
		exit 0
;;

	
	#03)
#$DIALOG --infobox "Axel nu accepta cookies ... $film1" 10 60

#			echo -ne "\b\b\b\b" #|$DIALOG --gauge "Descarc.." 6 50 10
#		exit 0
#;
	03)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;

	04)	filmnou ;;

	05)	exit 0 ;;
  esac

 }


$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme cinemaxx" --clear \
          --menu ":::" 25 30 25 \
	"01" "Noi aparitii" \
	"02" "Dupa gen" 2>$tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`



case "$selectat" in

	01) 
$DIALOG --infobox "Procesez..." 5 15

if [ ! -f $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx ];then
	
	wget -qO - www.cinemaxx.ro/rss.php|grep '<title>\|<link>'|sed ':a;N;$!ba'>$HOME/.tvmaxe-cli/.tmp/noi_cinemaxx.tmp

	cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx.tmp|grep title|sed 's/ /_/g;s/[<>]/ /g'|awk '{print $3}'|sed '1d' > $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx_title.tmp

	cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx.tmp|grep link|sed 's/ /_/g;s/[<>]/ /g'|awk '{print $3}'|sed '1d' > $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx_link.tmp
	
	paste $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx_title.tmp $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx_link.tmp | column -s $'\t' -t > $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx
fi

		

filmenoi=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $filmenoi  2> $tempfile
      		selectie0=$?
		abandon
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $2}'|sed -n "${nr_film_nou}p"`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $1}'|sed 's/_/ /g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		
		embed=`wget -qO - $adresa|grep pm-embed-code|sed -e 's/^.*\(src=.*\).*$/\1/;s/"/ /g'|awk '{print $2}'`


		filtru_film
		
$DIALOG --infobox "Procesez..." 5 15
		
;;


02)
$DIALOG --infobox "Procesez..." 5 15

wget -qO - http://cinemaxx.ro|sed -n "/>Categoria/,/>Articole/ p"|grep browse-filme|sed 's/ /_/g;s/[<>"]/ /g;s/_//g'|awk '{print $5,$3}'>$HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx
categorii=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Categorii" --clear \
         	 --menu ":::" 30 50 30 $categorii  2> $tempfile
      		selectie0=$?
		abandon
		nume_categorie=`cat $tempfile`
		nr_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|sed -n "/$nume_categorie/="`
		adresa_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|awk '{print $2}'|sed -n "${nr_categorie}p"`


nr_pagini=`wget -qO - $adresa_categorie|sed -n '/pagination/,/pre-footer/ p'|grep browse|sed '$d'|sed -n '$p'|sed 's/<[^>]*>/ /g'`

		adresa_categorie_paginare=`echo $adresa_categorie|sed 's/videos-/videos- /'`
		schelet_paginare=`echo $adresa_categorie_paginare|awk '{print $1}'`
i=1
		for p in `seq 1 $nr_pagini` ; do
			wget -qO - $schelet_paginare$(( i++ ))-date.html|sed -n "/videolist/,/pagination/ p" >> $HOME/.tvmaxe-cli/.tmp/categorie.tmp
			
			$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done

cat $HOME/.tvmaxe-cli/.tmp/categorie.tmp|grep '"title"'|sed 's/ /_/g;s/[<>]/ /g'|awk '{print $2}'>$HOME/.tvmaxe-cli/.tmp/categorie_title

cat $HOME/.tvmaxe-cli/.tmp/categorie.tmp|grep href|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'>$HOME/.tvmaxe-cli/.tmp/categorie_link

paste $HOME/.tvmaxe-cli/.tmp/categorie_title $HOME/.tvmaxe-cli/.tmp/categorie_link | column -s $'\t' -t >$HOME/.tvmaxe-cli/.tmp/categorie


filme_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "$nume_categorie" --clear \
         	 --menu ":::" 30 50 30 $filme_categorie  2> $tempfile
      		selectie0=$?
		abandon
		film_categorie=`cat $tempfile`
		nr_film_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|sed -n "/$film_categorie/="`
		adresa_film=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $2}'|sed -n "${nr_film_categorie}p"`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $1}'|sed -n "${nr_film_categorie}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		
		embed=`wget -qO - $adresa_film|grep pm-embed-code|sed -e 's/^.*\(src=.*\).*$/\1/;s/"/ /g'|awk '{print $2}'`
		
		filtru_film

$DIALOG --infobox "Procesez..." 5 15
		

		 rm $HOME/.tvmaxe-cli/.tmp/categorie
;;
esac


meniufilm
exit 0