#! /bin/bash
source config
ext=.flv
		abandon () {
		if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
			exit 0
 		fi
 					}

 		despre_film () {
			$DIALOG --infobox "Procesez..." 5 15
			$DIALOG --infobox "$descriere" 30 50 ; sleep 5


						}



meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcati" \
	"04" "Adaugati la favorite" \
	"05" "Reveniti" \
	"06" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 5 30
		$player  $nume1 $film1  &>/dev/null
		$postplay
		exit 0
;;

	02)	

		wget -O $salvare/$nume1$ext $film1 &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay  &>/dev/null
		killall wget 
		exit 0
;;

	03)


		axel -o $salvare/$nume1$ext $film1 2>&1 |grep "%]"| sed -u -e "s,\.,,g;s/\]//" | awk '{printf("\b\b\b\b%4s", $2)}' 2>&1
			echo -ne "\b\b\b\b" #|$DIALOG --gauge "Descarc.." 6 50 10
		exit 0
;;

	04)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;

	05)	filmnou ;;

	06)	exit 0 ;;
  esac

 }


$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme cinemaxx" --clear \
          --menu ":::" 25 30 25 \
	"01" "Noi aparitii" \
	"02" "Dupa gen" 2>$tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`



case "$selectat" in

	01) 
$DIALOG --infobox "Procesez..." 5 15

if [ ! -f $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx ];then
	#wget -qO - http://cinemaxx.co/rss.php|sed ':a;N;$!ba;s/\n//g'|sed 's/<title>/\n/g;s/ /_/g;s/[<>]/ /g'|sed '1,2d'|awk '{print $1,$5}'>$HOME/.tvmaxe-cli/.tmp/noi_cinemaxx
	wget -qO - http://cinemaxx.co/newvideos.html|sed -n "/videolist/,/pagination/ p"|sed ':a;N;$!ba;s/\n//g'|sed 's/href/\n/g;s/ /_/g;s/["<>]/ /g'|sed '1d'|awk '{print $8,$2}'>$HOME/.tvmaxe-cli/.tmp/noi_cinemaxx
fi

		

filmenoi=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $filmenoi  2> $tempfile
      		selectie0=$?
		abandon
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $2}'|sed -n "${nr_film_nou}p"`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi_cinemaxx|awk '{print $1}'|sed 's/_/ /g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		descriere=`wget -qO - $adresa|sed -n '/description text-exp/,/video-tags/ p'|sed 's/<[^>]*>/ /g'`
		embed=`wget -qO - $adresa|grep pm-embed-code|sed -e 's/^.*\(src=.*\).*$/\1/;s/"/ /g'|awk '{print $2}'`
		upload=`wget -qO - $embed|grep vk|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
$DIALOG --infobox "Procesez..." 5 15
		wget -qO - $upload|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse
	
 #film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')
 $DIALOG --infobox "Procesez..." 5 15
;;


02)
$DIALOG --infobox "Procesez..." 5 15

wget -qO - http://cinemaxx.co|sed -n "/>Categoria/,/>Articole/ p"|grep browse-filme|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $5,$3}'>$HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx
categorii=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Categorii" --clear \
         	 --menu ":::" 30 50 30 $categorii  2> $tempfile
      		selectie0=$?
		abandon
		nume_categorie=`cat $tempfile`
		nr_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|sed -n "/$nume_categorie/="`
		adresa_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_cinemaxx|awk '{print $2}'|sed -n "${nr_categorie}p"`


nr_pagini=`wget -qO - $adresa_categorie|sed -n '/pagination/,/footerwrapper/ p'|grep browse|sed '$d'|sed -n '$p'|sed 's/<[^>]*>/ /g'`

		adresa_categorie_paginare=`echo $adresa_categorie|sed 's/videos-/videos- /'`
		schelet_paginare=`echo $adresa_categorie_paginare|awk '{print $1}'`
i=1
		for p in `seq 1 $nr_pagini` ; do
			wget -qO - $schelet_paginare$(( i++ ))-date.html|sed -n "/videolist/,/pagination/ p"|sed ':a;N;$!ba;s/\n//g'|sed 's/href/\n/g;s/ /_/g;s/["<>]/ /g'|sed '1d'|awk '{print $8,$2}'>>$HOME/.tvmaxe-cli/.tmp/categorie
			$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done

filme_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "$nume_categorie" --clear \
         	 --menu ":::" 30 50 30 $filme_categorie  2> $tempfile
      		selectie0=$?
		abandon
		film_categorie=`cat $tempfile`
		nr_film_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|sed -n "/$film_categorie/="`
		adresa_film=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $2}'|sed -n "${nr_film_categorie}p"`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $1}'|sed -n "${nr_film_categorie}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		#descriere=`wget -qO - $adresa_film|sed -n '/description text-exp/,/video-tags/ p'|sed 's/<[^>]*>/ /g'`
		embed=`wget -qO - $adresa_film|grep pm-embed-code|sed -e 's/^.*\(src=.*\).*$/\1/;s/"/ /g'|awk '{print $2}'`
		upload=`wget -qO - $embed|grep vk|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`


$DIALOG --infobox "Procesez..." 5 15
		wget -qO - $upload|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse

		 rm $HOME/.tvmaxe-cli/.tmp/categorie
;;
esac

film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')

#despre_film

meniufilm
exit 0