#! /bin/bash
source config
nume_tv=`cat /tmp/tvmaxe-cli/adr`
	divertisment(){
		piesepl=`cat /tmp/tvmaxe-cli/divertisment|wc -l`
		nume=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $1}'|sed -n "${nr_linie_colectie}p"`
		nume1=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $1}'|sed -n "${nr_linie_colectie}p"`
		adresa=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		testt=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $3}'|sed -n "${nr_linie_colectie}p"`
		if [[ "$testt" = "www.220.ro" ]];then
		funny=`wget -qO - $adresa|grep source|sed "s/ /_/g;s/'/ /g"|awk '{print $2}'`
		elif [[ "$testt" = "www.trilulilu.ro" ]];then
		echo `wget -qO - "$adresa"|grep userid|sed "s/ /_/g;s/,/\n /g"|grep 'server\|type\|source\|hash\|userid\|key'`>/tmp/tvmaxe-cli/divertisment1
		funny=`cat /tmp/tvmaxe-cli/divertisment1|sed 's/[=:]/ /g'|awk '{print "http://fs"$7".trilulilu.ro/stream.php?type=video&source=site&hash="$5"&username="$3"&key=&format=mp4-360p"}'|sed 's/"//g'`
		elif [[ "$testt" = "izismile.com" ]];then
		funny=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`;fi
		ext=.mp4
		}
listare_divertisment (){

		wget -qO - http://st.220.t1.ro/rss/top|sed 's/<title>/\n/g;s/ /_/g;s/[<"?]/ /g'|grep href|awk '{print $1,$4,"www.220.ro"}'>/tmp/tvmaxe-cli/divertisment


		wget -qO - "http://www.trilulilu.ro/video-haioase?cele-mai-tari&azi"|grep '<span class="title"><a href='|sed 's/ /_/g;s/["><]/ /g'|awk '{print $5,$4,"www.trilulilu.ro"}'>>/tmp/tvmaxe-cli/divertisment
		
		wget -qO - http://izismile.com/videos/|grep "config: {"|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'|sed 's/\.flv/ /;s/\// /g'|awk '{print $7,$1"//"$2"/"$3"/"$4"/"$5"/"$6"/"$7".flv","izismile.com"}'>>/tmp/tvmaxe-cli/divertisment

colectie=`cat /tmp/tvmaxe-cli/divertisment|awk '{print $1,"off"}'|nl`
}
############################################
$DIALOG --infobox "\nCaut divertisment" 5 30
listare_divertisment
	$DIALOG --backtitle "tvmaxe-cli" \
          	--checklist ":::" 80 50 80 $colectie 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nr_linie=`cat $tempfile`
nr_alese=`echo $tempfile|wc -w`
############################################
	$DIALOG --backtitle "tvmaxe-cli" \
	 	--title "| Divertisment |" --clear \
          	--menu ":::" 25 30 25 \
	"01" "Reda selectia" \
	"02" "Adauga la favorite*" \
	"03" "Descarca selectia" \
	"04" "Reda toate" \
	"05" "Deascarca toate" \
	"06" "Reveniti" 2>$tempfile
selectie0=$?
  selectat=`cat $tempfile`
  
  divertisment
  case "$selectat" in

	01) 
		./abandon &
		for nr_linie_colectie in  $nr_linie ; do

	divertisment

   			$player "$funny" $postplay &>/dev/null

		done
;;

	02)
	$DIALOG --backtitle "tvmaxe-cli" \
		--title "Creati o lista sau adaugati postul la o lista existenta: " \
		--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
	selectie0=$?
	selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
for nr_linie_colectie in  $nr_linie ; do

divertisment
			echo "$nume $funny" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
done
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi
;;

	03)
	for nr_linie_colectie in  $nr_linie ; do

	divertisment
		
wget -O $salvare/$nume$ext $funny 2>&1 | \
awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | $DIALOG --gauge "Descarc..." 6 50 1
	done
;;
	04)
		./abandon &
		for nr_linie_colectie in `seq 1 $piesepl` ; do
		divertisment
		
   			$player "$funny" $postplay &>/dev/null

		done
;;
	05)
		
		for nr_linie_colectie in `seq 1 $piesepl` ; do
		divertisment
		wget -O $salvare/$nume$ext $funny 2>&1 | \
		awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | $DIALOG --gauge "Descarc..." 6 50 1
		done
;;
	06)exit 0;;
esac
############################################

