#! /bin/bash
source config
nume_tv=`cat $HOME/.tvmaxe-cli/.tmp/adr`
	divertisment(){
		piesepl=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|wc -l`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $1}'|sed -n "${nr_linie_colectie}p"`
		nume1=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $1}'|sed -n "${nr_linie_colectie}p"`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		testt=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $3}'|sed -n "${nr_linie_colectie}p"`
		if [[ "$testt" = "www.220.ro" ]];then
		funny=$adresa
		#elif [[ "$testt" = "www.trilulilu.ro" ]];then
		#echo `wget -qO - "$adresa"|grep userid|sed "s/ /_/g;s/,/\n /g"|grep 'server\|type\|source\|hash\|userid\|key'`>$HOME/.tvmaxe-cli/.tmp/divertisment1
		#funny=`cat $HOME/.tvmaxe-cli/.tmp/divertisment1|sed 's/[=:]/ /g'|awk '{print "http://fs"$7".trilulilu.ro/stream.php?type=video&source=site&hash="$5"&username="$3"&key=&format=mp4-360p"}'|sed 's/"//g'`
		elif [[ "$testt" = "izismile.com" ]]
			then
			
		adr_smile=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		funny=`wget -qO - $adr_smile|grep youtube|sed 's/"/ /g'|sed -e 's/^.*\(youtube[^ ,]*\).*$/\1/'|awk '{print "https://youtube.com/"$1}'`
	#elif [[ "$testt" = "metacafe" ]]
		#then
		#adr_metacafe=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		#funny=`wget -qO - $adr_metacafe|grep mccont|sed -n '1p'|sed 's/ /_/g;s/vl.mccont/ http:\/\/vl.mccont/;s/mp4/mp4 /g'|awk '{print $2}'|sed 's/\%5C/\//g;s/\%2F//g;s/\%25/\%/g'`
	elif [[ "$testt" = "ochevidets" ]]
		then
		adr_ochevidets=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
		funny=`wget -qO - $adr_ochevidets|grep Скачать|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
	fi
		ext=.mp4
		}
listare_divertisment (){
$DIALOG --infobox "220.ro" 5 20
		wget -qO - http://st.220.t1.ro/rss/top|sed 's/<title>/\n/g;s/ /_/g;s/[<"?]/ /g'|grep href|awk '{print $1,$4,"www.220.ro"}'>$HOME/.tvmaxe-cli/.tmp/divertisment

#$DIALOG --infobox "trilulilu.ro" 5 20
		#wget -qO - "http://www.trilulilu.ro/video-haioase?cele-mai-tari&azi"|grep '<span class="title"><a href='|sed 's/ /_/g;s/["><]/ /g'|awk '{print $5,$4,"www.trilulilu.ro"}'>>$HOME/.tvmaxe-cli/.tmp/divertisment
$DIALOG --infobox "izismile.com" 5 20		
		wget -qO - http://m.izismile.com/videos/|grep m.izismile|grep h2|sed 's/ /_/g;s/["<>]/ /g'|awk '{print $4,$2,"izismile.com"}'>>$HOME/.tvmaxe-cli/.tmp/divertisment
#$DIALOG --infobox "metacafe.com" 5 20
		#wget -qO - http://www.metacafe.com/darwin-award-winners|grep "/watch/"|grep ItemTitle|sed 's/ /_/g;s/"/ /g'|awk '{print $8,"http://www.metacafe.com"$6,"metacafe"}'>>$HOME/.tvmaxe-cli/.tmp/divertisment
$DIALOG --infobox "ochevidets.ru" 5 20
		wget -qO - http://www.ochevidets.ru/best/|grep item_title|sed 's/ /_/g;s/["<>]/ /g'|awk '{print $6,"http://www.ochevidets.ru"$5,"ochevidets"}'>>$HOME/.tvmaxe-cli/.tmp/divertisment

colectie=`cat $HOME/.tvmaxe-cli/.tmp/divertisment|awk '{print $1,"off"}'|nl`
}
############################################
$DIALOG --infobox "\nCaut divertisment" 5 30
listare_divertisment
	$DIALOG --backtitle "tvmaxe-cli" \
          	--checklist ":::" 80 80 80 $colectie 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nr_linie=`cat $tempfile|sed 's/"//g'`
nr_alese=`echo $tempfile|wc -w`
############################################
	$DIALOG --backtitle "tvmaxe-cli" \
	 	--title "| Divertisment |" --clear \
          	--menu ":::" 25 60 25 \
	"01" "Reda selectia" \
	"02" "Adauga la favorite*" \
	"03" "Descarca selectia" \
	"04" "Reda toate" \
	"05" "Deascarca toate" \
	"06" "Reveniti" 2>$tempfile
selectie0=$?
  selectat=`cat $tempfile`
  
  divertisment
  case "$selectat" in

	01) 
		./abandon &
		for nr_linie_colectie in  $nr_linie ; do

	divertisment
echo Funny $funny
   			youtube-dl "$funny" -o -|$player - &>/dev/null
   			$postplay 
   			killall youtube-dl

		done
		exit 0
;;

	02)
	$DIALOG --backtitle "tvmaxe-cli" \
		--title "Creati o lista sau adaugati postul la o lista existenta: " \
		--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
	selectie0=$?
	selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
for nr_linie_colectie in  $nr_linie ; do

divertisment
			echo "$nume $funny" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
done
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi
;;

	03)
	for nr_linie_colectie in  $nr_linie ; do

	divertisment
		
youtube-dl $funny  -o $salvare/$nume$ext 
	done
	exit 0
;;
	04)
		./abandon &
		for nr_linie_colectie in `seq 1 $piesepl` ; do
		divertisment
		
   			youtube-dl "$funny" -o - $player -  &>/dev/null
   			$postplay

		done
		exit 0
;;
	05)
		
		for nr_linie_colectie in `seq 1 $piesepl` ; do
		divertisment
		youtube-dl $funny -o $salvare/$nume$ext
		done
		exit 0
;;
	06)exit 0
;;

esac

############################################
killall $player youtube-dl
exit 0