#! /bin/bash

OPTIUNE="Evenimente Cautati_stream_tv Parasiti"
select opt in $OPTIUNE;do
	if [[ "$opt" = "Evenimente" ]]
		then
echo "Evenimente sopcast"
#http://sopcast.ucoz.com/news/rss/
wget -qO - http://sopcast.ucoz.com/news/rss/|grep -Ev 'description>|category>|<dc:|guid>|pubDate>|item>|channel>|rss'|sed '1,5d'|sed ':a;N;$!ba;s/\n/ /g'|sed 's/<\/link>/\n/g;s/<title>//g;s/<link>//g;s/ /|/g;s/<\/title>/ /g' > $HOME/.tvmaxe-cli/.tmp/evenimente

cat $HOME/.tvmaxe-cli/.tmp/evenimente|awk '{print $1}'|sed 's/|/ /g'|nl
read -p "Alegeti evenimentul: " eveniment 
link=`cat $HOME/.tvmaxe-cli/.tmp/evenimente|awk '{print $2}'|sed 's/|/ /g'|sed -n "${eveniment}p"`
wget -qO - $link|grep -o 'sop://[^ ,]\+'
echo "##################"
echo "1-Evenimente 2-Cautati_stream_tv 3-Parasiti"
	elif [[ "$opt" = "Cautati_stream_tv" ]]
		then
read -p "ce cautati? " cautare
echo
echo "Gasit pe ucoz:"
wget -qO - http://sopcast.ucoz.com/search/?q="$cautare"|grep "sop://"|sed 's/<b>/\n/g;s/<\/b>//g;s/<\/div>//g;s/sop:/ sop:/g'|grep "sop://"|nl
echo
echo "Gasit pe cool-tv:"
wget -qO - http://www.cool-tv.ro/m/|grep sop|sed 's/ /_/g;s/"/ /g;s/.gif//'|sed '$d'|awk '{print $4,$2}'|grep "$cautare"|nl
echo
echo "Gasit pe etvonline:"
wget -qO - http://www.m.etvonline.ro/|grep sop|sed 's/ /_/g;s/"/ /g;s/\.jpg//;s/\.png//;s/\.gif//'|awk '{print $4,$2}'|grep "$cautare"|nl
echo "##################"
echo "1-Evenimente 2-Cautati_stream_tv 3-Parasiti"
elif [[ "$opt" = "Parasiti" ]]
	then 
	exit 0
else 
	echo "Ati ales gresit, mai incercati."
fi
done