#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
  source config
fi

listatvro=`cat $HOME/.tvmaxe-cli_favorite|awk '{print $1"--"NR,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Lista |" --clear \
          --menu ":::" 30 35 30 $listatvro 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
  
nume_post_tv=`cat $tempfile`

nr_post_tv=`echo $nume_post_tv|sed 's/--/ /g'|awk '{print $2}'`

cat $HOME/.tvmaxe-cli_favorite|sed -n "${nr_post_tv}p" > $HOME/.tvmaxe-cli/.tmp/adr

adresa_tv=`cat $HOME/.tvmaxe-cli/.tmp/adr|awk '{print $2}'`

$DIALOG --infobox " Nume TV: $nume_post_tv \n Adresa: $adresa_tv" 6 50

    sleep 1

./filtrutv