#! /bin/bash 

source config

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme" --clear \
          --menu ":::" 25 30 25 \
	"01" "990.ro" \
	"02" "cinemaxx.rs" \
	"03" "cautare film" \
	"04" "redati din favorite" 2>$tempfile
  selectie0=$?

  selectat=`cat $tempfile`
case "$selectat" in
	01) ./990 ;;
	02) ./cinemaxx ;;
	03) ./cautare_film ;;
	04) echo "in lucru" ;;
esac
exit 0
