#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
ext=.mp4
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
exit 0
  fi
}

despre_film () {
$DIALOG --infobox "Procesez..." 5 15
$DIALOG --infobox "$descriere" 30 50 ; sleep 5
}

meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcati" \
	"04" "Adaugati la favorite" \
	"05" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 5 30
		$player $film1  &>/dev/null
		$postplay
		exit 0
;;

	02)	wget -O $salvare/$nume1$ext $film1 &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay  &>/dev/null
		killall wget 
		exit 0
;;

	03)	axel -o $salvare/$nume1$ext $film1 2>&1 |grep "%]"| sed -u -e "s,\.,,g;s/\]//" | awk '{printf("\b\b\b\b%4s", $2)}' 2>&1
			echo -ne "\b\b\b\b" #|$DIALOG --gauge "Descarc.." 6 50 10
		exit 0
;;

	04)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;


	05)	exit 0 ;;
  esac

 }



wget -qO - http://filmeonlinenoi.ro/|sed -n "/genres/,/sortmenu/ p"|grep href|sed 's/ /_/g;s/["<>]/ /g'|sed '1d'|awk '{print $6,"http://filmeonlinenoi.ro"$3}'>$HOME/.tvmaxe-cli/.tmp/categorii_filmeonlinero
categorii=`cat $HOME/.tvmaxe-cli/.tmp/categorii_filmeonlinero|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Categorii" --clear \
         	 --menu ":::" 30 50 30 $categorii  2> $tempfile
      		selectie0=$?
		abandon
		nume_categorie=`cat $tempfile`
		nr_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_filmeonlinero|sed -n "/$nume_categorie/="`
		adresa_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorii_filmeonlinero|awk '{print $2}'|sed -n "${nr_categorie}p"`


nr_pagini=`wget -qO - $adresa_categorie|grep wp-pagenavi|sed -n '1p'|sed 's/<[^>]*>//g;s/[A-Za-z]*//g'|awk '{print $NF}'`


i=1
		for p in `seq 1 $nr_pagini` ; do
			wget -qO - $adresa_categorie/page/$(( i++ ))/|grep 'id="post"'|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $5,$4}'>>$HOME/.tvmaxe-cli/.tmp/categorie
			$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done


filme_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
		  --title "$nume_categorie" --clear \
         	 --menu ":::" 30 50 30 $filme_categorie  2> $tempfile
      		selectie0=$?
		abandon
		film_categorie=`cat $tempfile`
		nr_film_categorie=`cat $HOME/.tvmaxe-cli/.tmp/categorie|sed -n "/$film_categorie/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/categorie|awk '{print $2}'|sed -n "${nr_film_categorie}p"`
		upload=`wget -qO - $adresa|grep vk.com|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g'|sed -n "${nr_film_categorie}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		wget -qO - $upload|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse


film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')

#despre_film


meniufilm
exit 0