#! /bin/bash 


if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme" --clear \
          --menu ":::" 25 30 25 \
	"01" "990.ro" \
	"02" "cinemaxx.rs"  2>$tempfile
  selectie0=$?

  selectat=`cat $tempfile`
case "$selectat" in
	01) ./990 ;;
	02) ./cinemaxx ;;
	
esac
exit 0
