#!/bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
########################################
player1=`echo $player3|awk '{print $1}'`
data=`date +%F_%R`
liste=`ls $HOME/.tvmaxe-cli/playlist|sed 's/\./ /'|grep " tv"|awk '{print $1}'`
post=$HOME/.tvmaxe-cli/.tmp/adr
adr=`cat $post|awk '{print $2}'|sed 's/|/ /g;s/"//g'`
nume_tv=`cat $post|awk '{print $1}'`
format=`cat $HOME/.tvmaxe-cli/.tmp/format|awk '{print $1}'`
radio=`cat $HOME/.tvmaxe-cli/.tmp/format|awk '{print $2}'`

sopcast_rpi () {
./qemu-i386 lib/ld-linux.so.2 --library-path lib ./sp-sc-auth $1 $2 $3
}

sopcast_pc () {
sp-sc-auth $1 $2 $3
}
cat $post|awk '{print $2}'|sed 's/\// /g;s/\./ /g'|awk '{print $2}'

protocol_tv (){
soptest=`cat $post|awk '{print $2}'|sed 's/\:/ /g;s/"//g'|awk '{print $1}'`
m3u8test=`cat $post|awk '{print $2}'|sed 's/?/ /'|sed -e 's/^.*\(m3u8[^ ,]*\).*$/\1/'`
#rtsptest=`cat $post|awk '{print $2}'|sed 's/:/ /g'|awk '{print $1}'`
numetv=`cat $post|awk '{print $1}'`
pls=`cat $post|awk '{print $2}'|sed 's/\./ /g'|awk '{ print $NF }'`
pls3=`cat $post|awk '{print $2}'|sed 's/\./ /g'|awk '{print $2}'`
superweb=`cat $post|awk '{print $2}'|sed 's/\// /g;s/\./ /g'|awk '{print $2}'`
if [[ "$soptest" = "sop" ]]; then protocol=sopcast
	elif [[ "$soptest" = "rtsp" ]]; then protocol=rtsp
	elif [[ "$soptest" = "rtmp" ]]; then protocol=rtmp
	elif [[ "$soptest" = "mms" ]]; then protocol=mms
	elif [[ "$soptest" = "acestream" ]]; then protocol=acestream
	elif [[ "$m3u8test" = "m3u8" ]]; then protocol=m3u8
	elif [[ "$pls" = "m3u8" ]]; then protocol=m3u8
	elif [[ "$pls" = "asf" ]]; then protocol=asf
	elif [[ "$pls" = "pls" ]]; then protocol=pls
	elif [[ "$pls" = "asx" ]]; then protocol=pls
	elif [[ "$pls" = "m3u" ]]; then protocol=m3u
	#elif [[ "$pls" = "m3u8" ]]; then protocol=m3u8
	elif [[ "$pls3" = "shoutcast" ]]; then protocol=shoutcast
	elif [[ "$pls3" = "youtube" ]]; then protocol=youtube
	elif [[ "$pls3" = "ustream" ]]; then protocol=livestream
	elif [[ "$pls3" = "livestream" ]]; then protocol=livestream
	elif [[ "$superweb" = "superweb" ]]; then protocol=superweb
	elif [[ "$superweb" = "vk" ]]; then protocol=vk
else 
	protocol=http
fi
	      }

inregistrare () {
		if [[ "$protocol" = "sopcast" ]]; then 
			$( $sopcast "$adr 8901 9901" &>/dev/null &)
			$DIALOG --infobox "incep inregistrarea in 20 sec" 5 35 ; sleep 20; wait 
#$procesare -y -i "http://localhost:9901 " -acodec copy -vcodec copy -f $format  $salvare/$numetv"_"$data.$format 2>/dev/null &
#sleep $delay
			wget -O $salvare/$numetv"_"$data.$format http://localhost:9901 &>/dev/null &
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null 
			killall wget $omoara_sopcast #$procesare
			#stty sane
		elif [[ "$protocol" = "acestream" ]]; then
		pid=`echo $adr|sed 's/\/\// /'|awk '{print $2}'`
		acestreamengine --client-console $adr &
		$DIALOG --infobox "incep inregistrarea in 20 sec" 5 35 ; sleep 20; wait 

			wget -O $salvare/$numetv"_"$data.$format http://localhost:6878/LOAD/PID=$pid &>/dev/null &
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null 
			killall wget acestream #$procesare
			
		elif [[ "$protocol" = "m3u8" ]]; then 
			$procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -vcodec copy -f $format  $salvare/$numetv"_"$data.$format 2>/dev/null & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
			sleep $delay
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null 
			killall $procesare
			stty sane
		elif [[ "$protocol" = "asf" ]]; then 
			$procesare -i "$adr" -acodec copy -vcodec copy -f $format $salvare/$numetv"_"$data.$format 2>/dev/null &
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
			sleep $delay
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null 
			killall $procesare
			stty sane
		elif [[ "$protocol" = "rtsp" ]];then 
			$procesare -y -i "$adr" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35 
			sleep $delay
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null 
			killall procesare
			stty sane
		elif [[ "$protocol" = "rtmp" ]]; then 
			$(rtmpdump -r $adr -o -|$procesare -y -i "-" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null) & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35 
			sleep $delay
			$player3 $salvare/$numetv"_"$data.$format &>/dev/null
			killall $procesare 
			stty sane
			killall rtmpdump
		elif [[ "$protocol" = "livestream" ]]; then 
			
			livestreamer $adr best -Q -f -o $salvare/$numetv"_"$data.mp4 &
			$DIALOG --infobox "inregistrez..." 5 35 
			
		elif [[ "$protocol" = "superweb" ]]; then
			film1=`wget -qO - $upload|grep "'file': '"|sed '1p'|sed "s/ /_/;s/'/ /g"|awk '{print $3}'|sed '$d'`
			key=`echo $adr|sed 's/[\/.html]/ /g'| awk '{print $NF}'`
			subtitrare1=`echo http://superweb.rol.ro/video/jw6/$key.srt`
			wget -O $salvare/$numetv.srt
			wget -O $salvare/$numetv.mp4 $film1 &
			$DIALOG --infobox "inregistrez..." 5 35 
			sleep $delay
			$player3 $salvare/$numetv.mp4 &>/dev/null

		elif [[ "$protocol" = "vk" ]]; then
			wget -qO - $adr|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse
			film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')
			wget -O $salvare/$numetv.mp4 $film1 &
			$DIALOG --infobox "inregistrez..." 5 35 
			sleep $delay
			$player3 $salvare/$numetv.mp4 &>/dev/null


		else
			if [ "$radio" == "radio" ]
				then

				if [[ "$protocol" = "pls" ]]
					then
					list="-playlist"
				else
					list=" "
				fi

				mplayer $list $adr -dumpstream -dumpfile $salvare/$numetv"_"$data.ts &>/dev/null &
				$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
				sleep $delay 
				$player $salvare/$numetv"_"$data.ts &>/dev/null 
				killall mplayer
				
					stty sane
			elif [ "$radio" == "tv" ]
				then
				
					#$procesare -i "$adr" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null &
					wget -O $salvare/$numetv"_"$data.$format $adr &>/dev/null &

					$DIALOG --infobox "inregistrez...,\nredau inregistrarea in $delay sec" 5 35
					sleep 20
					$player4 $salvare/$numetv"_"$data.$format &>/dev/null 
					killall wget
						

			fi		

		fi
		
}
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
}

#####################################################################
protocol_tv
if [[ "$protocol" = "youtube" ]]; then 

			$DIALOG --backtitle "tvmaxe-cli" \
	 			--title "| Youtube |" --clear \
          			--menu ":::" 25 35 25 \
				"01" "Reda" \
				"02" "Descarca" \
				"03" "Conversie wav" \
				"04" "Conversie mp3" \
				"05" "Reveniti" 2>$tempfile
				selectie0=$?
				abandon
 				selectat=`cat $tempfile`

			case "$selectat" in
				01) youtube-dl $adr -o -|$player3 - &>/dev/null || livestreamer $adr best -Q -o - |$player3 - &>/dev/null;exit 0 ;;
				02) cd $salvare;youtube-dl $adr;exit 0;;
				03) youtube-dl $adr -o -|$procesare -i "-" -vn -acodec pcm_s16le -ar 16000 -ac 1 -f wav $salvare/youtube$$.wav;exit 0;;
				04) youtube-dl $adr -o -|$procesare -i "-" -acodec libmp3lame -ac 2 -ab 128 -vn -y $salvare/youtube$$.mp3;exit 0;;
				05) exit 0;;
			esac
fi
		


$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume_tv" --clear \
          --menu ":::" 25 30 25 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Inregistrati in:" \
	"04" "Add_Favorite" \
	"05" "Reveniti" \
	"06" "Parasiti" 2>$tempfile
#stream-tv
  selectie0=$?

	abandon

  selectat=`cat $tempfile`
$DIALOG --infobox "Procesez... \n Protocol $protocol" 5 15
case "$selectat" in
01) 
	if [[ "$protocol" = "sopcast" ]]; then
		$($sopcast "$adr 8901 9901" &>/dev/null & )
		sleep 30
		wait 
		#$(testpost=`wget --spider http://localhost:9901  -qO -&>/dev/null 2>&1`)
		#if [ $? != 0 ]; then
		#	$DIALOG --infobox "Adresa inactiva" 5 35 ;sleep 2
		#else
			#$(wget -qO - http://localhost:9901|$player3 - &>/dev/null)
			$player3 http://localhost:9901 &>/dev/null
			killall $omoara_sopcast
			killall $player1
		#fi

	elif [[ "$protocol" = "acestream" ]]; then
		pid=`echo $adr|sed 's/\/\// /'|awk '{print $2}'`
		acestreamengine --client-console $adr &
		sleep 15
		wait
		$player3 http://localhost:6878/LOAD/PID=$pid
		killall acestreamengine
	elif [[ "$protocol" = "m3u8" ]]; then 
			$($procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -vcodec copy -f flv - 2>/dev/null|$player3 - &>/dev/null);stty sane

	elif [[ "$protocol" = "asf" ]]; then 
		if [[ "$player3" = "vlc" ]]; then $player3 $adr
		else
		$($procesare -i "$adr" -acodec copy -vcodec copy -f avi - 2>/dev/null|$player3 -  &>/dev/null);stty sane
		fi
	elif [[ "$protocol" = "rtsp" ]]; then 
			$($procesare -y -i "$adr" -acodec copy -vcodec copy -r 20 -f flv - 2>/dev/null|$player3 - &>/dev/null);stty sane
			
	elif [[ "$protocol" = "rtmp" ]]; then 
			
			rtmpdump -r $adr -o -|$player3 -
	elif [[ "$protocol" = "pls" ]]||[[ "$protocol" = "m3u" ]]||[[ "$protocol" = "shoutcast" ]];
	then
			
			$player4 -playlist $adr 2>/dev/null|grep --line-buffered 'Name\|Genre\|Website\|ICY' #> $HOME/.tvmaxe-cli/.tmp/radio_info &
			#sleep 3
			#while read line < $HOME/.tvmaxe-cli/.tmp/radio_info; 
			#do
    		#$DIALOG --infobox "$line" 10 60
    		#sleep 30
			#done
			#wait
	elif [[ "$protocol" = "livestream" ]]
		then 
			livestreamer $adr best -Q -O |$player3 - &>/dev/null
	elif [[ "$protocol" = "superweb" ]]
		then
		film1=`wget -qO - $adr|grep "'file': '"|sed "s/ /_/;s/'/ /g"|awk '{print $3}'|sed '$d'`
		key=`echo $adr|sed 's/[\/.html]/ /g'| awk '{print $NF}'`
		subtitrare1=`echo http://superweb.rol.ro/video/jw6/$key.srt`
		$player3 $film1 -sub $subtitrare1

	elif [[ "$protocol" = "vk" ]]; then
			wget -qO - $adr|sed -n '/video_host/,/video_vtag/ p'|sed "s/ /_/g;s/'/ /g"|awk '{print $2}' > $HOME/.tvmaxe-cli/.tmp/surse

			film1=$(echo `cat $HOME/.tvmaxe-cli/.tmp/surse`|awk -v rez=$rez '{print $1"u"$2"/videos/"$3"."rez".mp4"}')
			$player3 $film1

	else
			#exec 2> /dev/null
			$player3 $adr 2>/dev/null|grep --line-buffered 'Name\|Genre\|Website\|ICY'
			 #$($procesare -y -i "$adr" -acodec copy -vcodec copy -f avi - 2>/dev/null|$player3 - &>/dev/null);stty sane

			
			#$player3 "$adr" &> /dev/null & #|tee $HOME/.tvmaxe-cli/.tmp/datehttp &
			#$DIALOG --backtitle "tvmaxe-cli" \
			#		--title "| $numetv |" \
			#		--msgbox "\nDoriti sa intrerupeti redarea?" 10 50
			#killall $player1
			#datehttp=`cat $HOME/.tvmaxe-cli/.tmp/datehttp`
			#$DIALOG --infobox "$datehttp" 30 35
	fi
	
;;
	02) inregistrare


;;
	03)		
			data_t=`date '+%F %R'`
			$DIALOG	--backtitle "tvmaxe-cli" \
				--title "| Temporizator |" \
				--form "\n Setati timpul in format $data" 25 35 16 \
			"inceput:" 1 1 "$data_t" 1 10 26 30 \
			"sfarsit:" 2 1 "$data_t" 2 10 26 30 \
			2>$tempfile
	selectie0=$?
	abandon
	inceput_rec=`cat $tempfile|sed -n '1p'`
	sfirsit_rec=`cat $tempfile|sed -n '2p'`
	export sfirsit_rec
	#http://stackoverflow.com/questions/645992/bash-sleep-until-a-specific-time-date
		data_curenta=$(date +%s)
		inceput=$(date -d "$inceput_rec" +%s)
		sfirsit=$(date -d "$sfirsit_rec" +%s)
		vegetare=$(( $inceput - $data_curenta ))
		apocalipsa=$(( $sfirsit - $inceput ))
		export apocalipsa
		$DIALOG --infobox "vegetez pentru $vegetare sec.\npina la $inceput_rec" 5 35
		sleep $vegetare
		$DIALOG --infobox "incep inregistrarea" 5 35 ; sleep 3
		./timer_inregistrare &
		inregistrare
;;

	04)
	
	
			echo "$nume_tv $adr" >> $HOME/.tvmaxe-cli_favorite
		
;;
	05) abandon ;;
	06) exit 0;;
esac
exit 0
