#!/bin/bash
source config
########################################
player1=`echo $player|awk '{print $1}'`
data=`date +%F_%R`
liste=`ls $HOME/.tvmaxe-cli/playlist|sed 's/\./ /'|grep " tv"|awk '{print $1}'`
post=/tmp/tvmaxe-cli/adr
adr=`cat $post|awk '{print $2}'|sed 's/|/ /g;s/"//g'`
nume_tv=`cat $post|awk '{print $1}'`
format=`cat /tmp/tvmaxe-cli/format|awk '{print $1}'`
radio=`cat /tmp/tvmaxe-cli/format|awk '{print $2}'`
protocol_tv (){
soptest=`cat $post|awk '{print $2}'|sed 's/[":]/ /g'|awk '{print $1}'`
m3u8test=`cat $post|awk '{print $2}'|sed 's/?/ /'|sed -e 's/^.*\(m3u8[^ ,]*\).*$/\1/'`
rtsptest=`cat $post|awk '{print $2}'|sed 's/:/ /g'|awk '{print $1}'`
numetv=`cat $post|awk '{print $1}'`
pls=`cat $post|awk '{print $2}'|sed 's/\./ /g'|awk '{ print $NF }'`
pls3=`cat $post|awk '{print $2}'|sed 's/\./ /g'|awk '{print $2}'`
youtube_m=`cat $post|awk '{print $2}'|sed 's/\./ /g'|awk '{print $2}'`
if [[ "$soptest" = "sop" ]];then protocol=sopcast
	elif [[ "$soptest" = "rtsp" ]]; then protocol=rtsp
	elif [[ "$soptest" = "rtmp" ]]; then protocol=rtmp
	elif [[ "$soptest" = "mms" ]]; then protocol=mms
	elif [[ "$m3u8test" = "m3u8" ]]; then protocol=m3u8
	elif [[ "$pls" = "m3u8" ]]; then protocol=m3u8
	elif [[ "$pls" = "asf" ]]; then protocol=asf
	elif [[ "$pls" = "pls" ]]; then protocol=pls
	elif [[ "$pls" = "asx" ]]; then protocol=pls
	elif [[ "$pls" = "m3u" ]]; then protocol=m3u
	elif [[ "$pls3" = "shoutcast" ]]; then protocol=shoutcast
	elif [[ "$pls3" = "youtube" ]]; then protocol=youtube
	elif [[ "$youtube_m" = "youtube" ]]; then protocol=youtube
else 
	protocol=http
fi
	      }

inregistrare () {
		if [[ "$protocol" = "sopcast" ]]; then 
			$(sp-sc $adr 8901 9901 &>/dev/null &)
			$DIALOG --infobox "incep inregistrarea in 20 sec" 5 35 ; sleep 20; wait 
#$procesare -y -i "http://localhost:9901 " -acodec copy -vcodec copy -f $format  $salvare/$numetv"_"$data.$format 2>/dev/null &
#sleep $delay
			wget -O $salvare/$numetv"_"$data.$format http://localhost:9901 &>/dev/null &
			$player $salvare/$numetv"_"$data.$format &>/dev/null 
			killall wget sp-sc #$procesare
			#stty sane
			
		elif [[ "$protocol" = "m3u8" ]]; then 
			$procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -vcodec copy -f $format  $salvare/$numetv"_"$data.$format 2>/dev/null & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
			sleep $delay
			$player $salvare/$numetv"_"$data.$format &>/dev/null 
			killall $procesare
			stty sane
		elif [[ "$protocol" = "asf" ]]; then 
			$procesare -i "$adr" -acodec copy -vcodec copy -f $format $salvare/$numetv"_"$data.$format 2>/dev/null &
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
			sleep $delay
			$player $salvare/$numetv"_"$data.$format &>/dev/null 
			killall $procesare
			stty sane
		elif [[ "$protocol" = "rtsp" ]];then 
			$procesare -y -i "$adr" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35 
			sleep $delay
			$player $salvare/$numetv"_"$data.$format &>/dev/null 
			killall procesare
			stty sane
		elif [[ "$protocol" = "rtmp" ]]; then 
			$(rtmpdump -r $adr -o -|$procesare -y -i "-" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null) & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35 
			sleep $delay
			$player $salvare/$numetv"_"$data.$format &>/dev/null
			killall $procesare 
			stty sane
			killall rtmpdump
		
		else
			if [ "$radio" == "radio" ]
				then
					$procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -f $format  $salvare/$numetv"_"$data.$format 2>/dev/null & 
			$DIALOG --infobox "inregistrez, redau inregistrarea in $delay sec" 5 35
			sleep $delay
					$player $salvare/$numetv"_"$data.$format &>/dev/null 
					killall $procesare
					stty sane
			elif [ "$radio" == "tv" ]
				then
				
					#$procesare -i "$adr" -acodec copy -vcodec copy -r 20 -f $format $salvare/$numetv"_"$data.$format 2>/dev/null &
					wget -O $salvare/$numetv"_"$data.$format $adr &>/dev/null &

					$DIALOG --infobox "inregistrez...,\nredau inregistrarea in $delay sec" 5 35
					sleep 20
					$player $salvare/$numetv"_"$data.$format &>/dev/null 
					killall wget
					#killall $procesare
					#stty sane	
			fi		

		fi
		
}
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
}

#####################################################################
protocol_tv
if [[ "$protocol" = "youtube" ]]; then 

			$DIALOG --backtitle "tvmaxe-cli" \
	 			--title "| Youtube |" --clear \
          			--menu ":::" 25 35 25 \
				"01" "Reda" \
				"02" "Descarca" \
				"03" "Conversie wav" \
				"04" "Conversie mp3" \
				"05" "Reveniti" 2>$tempfile
				selectie0=$?
				abandon
 				selectat=`cat $tempfile`

			case "$selectat" in
				01) youtube-dl $adr -o -|$player - &>/dev/null ;exit 0 ;;
				02) cd $salvare;youtube-dl --max-quality FORMAT $adr;exit 0;;
				03) youtube-dl $adr -o -|$procesare -i "-" -vn -acodec pcm_s16le -ar 16000 -ac 1 -f wav $salvare/youtube$$.wav;exit 0;;
				04) youtube-dl $adr -o -|$procesare -i "-" -acodec libmp3lame -ac 2 -ab 128 -vn -y $salvare/youtube$$.mp3;exit 0;;
				05) exit 0;;
			esac
fi
		


$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume_tv" --clear \
          --menu ":::" 25 30 25 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Inregistrati in:" \
	"04" "Add_Favorite" \
	"05" "Reveniti" \
	"06" "Parasiti" 2>$tempfile
#stream-tv
  selectie0=$?

	abandon

  selectat=`cat $tempfile`
$DIALOG --infobox "Procesez..." 3 15
case "$selectat" in
01) 
	if [[ "$protocol" = "sopcast" ]]; then
		$(sp-sc $adr 8901 9901 &>/dev/null &);sleep 15; wait 
		$(testpost=`wget --spider http://localhost:9901  -qO -&>/dev/null 2>&1`)
		if [ $? != 0 ]; then
			$DIALOG --infobox "Adresa inactiva" 5 35 ;sleep 2
$procesare -f lavfi -i testsrc -filter_complex "split=4[a][b][c][d];[a]pad=iw*4:ih[w];[b]lutyuv=u=128:v=128[x];[c]lutyuv=y=0:v=128[y];[d]lutyuv=y=0:u=128[z];[w][x]overlay=w:0[wx];[wx][y]overlay=w*2:0[wxy];[wxy][z]overlay=w*3:0" -f nut - | $player -
killall $procesare
			sleep 3
		else
			$($player http://localhost:9901 &>/dev/null); killall sp-sc ; break
		fi
	elif [[ "$protocol" = "m3u8" ]]; then 
			$($procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -vcodec copy -f flv - 2>/dev/null|$player - &>/dev/null);stty sane

	elif [[ "$protocol" = "asf" ]]; then 
		if [[ "$player" = "vlc" ]]; then $player $adr
		else
		$($procesare -i "$adr" -acodec copy -vcodec copy -f avi - 2>/dev/null|$player -  &>/dev/null);stty sane
		fi
	elif [[ "$protocol" = "rtsp" ]]; then 
			$($procesare -y -i "$adr" -acodec copy -vcodec copy -r 20 -f flv - 2>/dev/null|$player - &>/dev/null);stty sane
			
	elif [[ "$protocol" = "rtmp" ]]; then 
			
			rtmpdump -r $adr -o -|$player -
	elif [[ "$protocol" = "pls" ]]||[[ "$protocol" = "m3u" ]]||[[ "$protocol" = "shoutcast" ]];
	then
			$player -playlist $adr
		else
			#exec 2> /dev/null
			$player "$adr" &> /dev/null & #|tee /tmp/tvmaxe-cli/datehttp &
			$DIALOG --backtitle "tvmaxe-cli" \
					--title "| $numetv |" \
					--msgbox "\nDoriti sa intrerupeti redarea?" 10 50
			killall $player1
			#datehttp=`cat /tmp/tvmaxe-cli/datehttp`
			#$DIALOG --infobox "$datehttp" 30 35
	fi
	
;;
	02) inregistrare


;;
	03)		
			data_t=`date '+%F %R'`
			$DIALOG	--backtitle "tvmaxe-cli" \
				--title "| Temporizator |" \
				--form "\n Setati timpul in format $data" 25 35 16 \
			"inceput:" 1 1 "$data_t" 1 10 26 30 \
			"sfarsit:" 2 1 "$data_t" 2 10 26 30 \
			2>$tempfile
	selectie0=$?
	abandon
	inceput_rec=`cat $tempfile|sed -n '1p'`
	sfirsit_rec=`cat $tempfile|sed -n '2p'`
	export sfirsit_rec
	#http://stackoverflow.com/questions/645992/bash-sleep-until-a-specific-time-date
		data_curenta=$(date +%s)
		inceput=$(date -d "$inceput_rec" +%s)
		sfirsit=$(date -d "$sfirsit_rec" +%s)
		vegetare=$(( $inceput - $data_curenta ))
		apocalipsa=$(( $sfirsit - $inceput ))
		export apocalipsa
		$DIALOG --infobox "vegetez pentru $vegetare sec.\npina la $inceput_rec" 5 35
		sleep $vegetare
		$DIALOG --infobox "incep inregistrarea" 5 35 ; sleep 3
		./timer_inregistrare &
		inregistrare
;;

	04)
	
	$DIALOG --backtitle "tvmaxe-cli" \
		--title "Creati o lista sau adaugati postul la o lista existenta: " \
		--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
	selectie0=$?
	abandon
	selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume_tv $adr" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi
;;
	05) abandon ;;
	06) exit 0;;
esac
exit 0
