#! /bin/bash

#!/bin/bash
source config
######################################
ext=.flv
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
exit 0
  fi
}

despre_film () {
$DIALOG --infobox "Procesez..." 5 15
$DIALOG --infobox "$descriere" 30 50 ; sleep 5
}
subtitrare () {
		key=`echo $upload|sed 's/[\/.html]/ /g'| awk '{print $NF}'`
		subtitrare1=`echo http://superweb.rol.ro/video/jw6/$key.srt`
}
meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcati" \
	"04" "Adaugati la favorite" \
	"05" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 10 60
		subtitrare
		$DIALOG --infobox "Adresa Film: \n$film1 \n\nAdresa Subtitrare: \n$subtitrare1" 10 80
		echo $film1
		$player $film1  -sub $subtitrare1 &>/dev/null
		$postplay
		exit 0
;;

	02)	subtitrare
		$DIALOG --infobox "Adresa Film: \n$film1 \n\nAdresa Subtitrare: \n$subtitrare1" 10 80
		wget -O $salvare/$nume1.srt $subtitrare1 &>/dev/null 
		wget -O $salvare/$nume1$ext $film1 &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay &>/dev/null
		killall wget 
		exit 0
;;

	03)	subtitrare
		$DIALOG --infobox "Adresa Film: \n$film1 \n\nAdresa Subtitrare: \n$subtitrare1" 10 80
		wget -O $salvare/$nume1.srt $subtitrare1 &>/dev/null 
		sleep 0.5
		axel -o $salvare/$nume1$ext $film1 2>&1 |grep "%]"| sed -u -e "s,\.,,g;s/\]//" | awk '{printf("\b\b\b\b%4s", $2)}' 2>&1
			num=`echo -ne "\b\b\b\b"` 
			echo $num|$DIALOG --gauge "Descarc.." 6 50 10
		exit 0
		
;;

	04)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;


	05)	exit 0 ;;
  esac

 }

	$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme 990.ro" --clear \
          --menu ":::" 25 30 25 \
	"01" "Filme dupa gen" \
	"02" "Seriale dupa gen" \
	"03" "Parasiti"  2>$tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`
case "$selectat" in

	01) #filme dupa gen
	$DIALOG --infobox "Procesez..." 5 15
$DIALOG --infobox "Procesez..." 5 15

			 $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Seriale dupa gen |" --clear \
          --menu ":::" 25 30 25 \
"01" "Actiune" \
"02" "Animatie" \
"03" "Asitice"  \
"04" "Comedie" \
"05" "Desene-animate" \
"06" "Documentare" \
"07" "Drama" \
"08" "Horror" \
"09" "Romantic" \
"10" "SF" \
"11" "Thriller" \
 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`

  
  case "$selectat" in
01)		gen_film=actiune;;
02) 	gen_film=animatie;;
03)		gen_film=filme-asiatice;;	 
04)		gen_film=comedie;;
05)		gen_film=desene-animate;;
06)		gen_film=documentare;;
07)		gen_film=drama;;
08)		gen_film=horror;;
09)		gen_film=romantic;;
10)		gen_film=fantezie;;
11)		gen_film=thriller;;

	esac

$DIALOG --infobox "Procesez..." 5 15

	pagini_gen=`wget -qO - "http://www.fsplay.net/$gen_film" --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep "Page 1"|sed 's/<[^>]*>/ /g;s/[A-Za-z]*//g'|awk '{print $2}'`
	$DIALOG --infobox "Am gasit $pagini_gen pagini. Incep paginarea lor" 5 50		
sleep 2
		i=1
		for p in `seq 1 $pagini_gen` ; do
			wget -qO - "http://www.fsplay.net/$gen_film/page/$(( i++ ))" --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1"|grep cath2|sed 's/ /|/g;s/"/ /g;s/Vizioneaza|//g;s/|Film|Online|Subtitrat//g'|awk '{print $6,$4}'>>$HOME/.tvmaxe-cli/.tmp/filme_gen
		$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done
		filme_gen=`cat $HOME/.tvmaxe-cli/.tmp/filme_gen|awk '{print $1}'|nl`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "$nume_gen" --clear \
         	 	--menu ":::" 30 70 30 $filme_gen 2> $tempfile
      		selectie0=$?
		abandon
		nr_film_gen1=`cat $tempfile`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/filme_gen|awk '{print $2}'|sed -n "${nr_film_gen1}p"`
		server1=`wget -qO - $adresa --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep sfast|sed -n '1p'|sed "s/ /_/g;s/'/ /g"|awk '{print "http://www.990.ro/"$4}'`
		upload=`wget -qO - $server1 --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep superweb|sed "s/'//g;s/http/ http/g;s/[<>]/ /g"|awk '{print $4}'`
		film1=`wget -qO - $upload --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1" |grep "'file': '"|sed "s/ /_/;s/'/ /g"|awk '{print $3}'|sed '$d'`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/noi|awk '{print $1}'|sed 's/_/ /g;s/[\/\;\:\?]//g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`

		meniufilm
;;