#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
  source config
fi
liste_radio=`ls -a $HOME/.tvmaxe-cli/playlist|grep "raddio"|sed 's/\.raddio//g;s/\.//g'|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| RADIO |" --clear \
          --menu ":::" 30 35 30 $liste_radio 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nume_lista_radio=`cat $tempfile`

listaradio=`cat $HOME/.tvmaxe-cli/playlist/.$nume_lista_radio.raddio|awk '{print $1,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| RADIO |" --clear \
          --menu ":::" 30 35 30 $listaradio 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nume_post_radio=`cat $tempfile`
nr_post_radio=`cat $HOME/.tvmaxe-cli/playlist/.$nume_lista_radio.raddio|sed -n "/$nume_post_radio/="`
cat $HOME/.tvmaxe-cli/playlist/.$nume_lista_radio.raddio|sed -n "${nr_post_radio}p" > $HOME/.tvmaxe-cli/.tmp/adr

./filtrutv

