#! /bin/bash

Romania () {
$DIALOG --infobox "Actualizez liste radio.. \n Romania" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Romania.raddio  > $HOME/.tvmaxe-cli/playlist/.Romania.raddio
}

Moldova () {
$DIALOG --infobox "Actualizez liste radio.. \n R.Moldova" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Basarabia.raddio  > $HOME/.tvmaxe-cli/playlist/.Basarabia.raddio
}

Classic () {
$DIALOG --infobox "Actualizez liste radio.. \n Radio Classic" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Clasic.raddio  > $HOME/.tvmaxe-cli/playlist/.Clasic.raddio
}

Mix () {
$DIALOG --infobox "Actualizez liste radio.. \n Radio Mix" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Mix.raddio  > $HOME/.tvmaxe-cli/playlist/.Mix.raddio
}

Podcast () {
$DIALOG --infobox "Actualizez liste radio.. \n Podcast" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Podcast.raddio > $HOME/.tvmaxe-cli/playlist/.Podcast.raddio
}
#################################################
Romania
Moldova
Classic
Mix
Podcast
#################################################
exit 0
