#! /bin/bash
source config
git="https://raw.github.com/calvarr/tvmaxe-cli/master/"
fisiere=$(echo \
abandon \
actualizare \
adr_externa \
capstream \
ceas \
config \
configurare \
divertisment \
favorite \
filme \
filtrutv \
meniufilm \
radioclasic \
radiomd \
radiomix \
radioro \
README \
romaniatv \
scriptUP \
shoutcast \
teatrul_radiofonic \
timer_inregistrare \
tv \
tvlist \
tvmaxe-cli \
youtube \
youtube_tv)
nr_fisiere=`echo $fisiere|wc -w`
i=1;c=1
for i in $(seq 1 $nr_fisiere )
do
nume_fisier=`echo $fisiere|sed 's/ /\n/g'|sed -n "${i}p"`
url_fisier=`echo $fisiere|sed 's/ /\n/g'|sed -n "${i}p"|awk -v git=$git '{print git$1}'`
wget -O $HOME/.tvmaxe-cli/$nume_fisier $url_fisier
((c+=4));echo $c|$DIALOG --gauge "Actualizez $nume_fisier" 6 50 10
sleep 2
done
