#! /bin/bash

source config

abandon () {
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
	}
	$DIALOG --backtitle "tvmaxe-cli" \
		--title "Shoutcast" --clear \
         	--menu ":::" 30 35 30 \
		  "01" "Sorteaza pe genuri" \
		  "02" "Cauta un post radio" 2> $tempfile
      		selectie0=$?
	abandon
		selectat=`cat $tempfile`
case "$selectat" in
01)

		wget -qO - "http://www.shoutcast.com/?action=search&string=genres"|grep "href="|grep action|sed '/id=/d'|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $5,"http://www.shoutcast.com/radiolist.cfm"$4}'|sed '1d' > $HOME/.tvmaxe-cli/.tmp/shoutcast_genuri
		genuri=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_genuri|awk '{print $1,"|"}'|sed 's/\&amp;/\&/g'`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Shoutcast-gen" --clear \
         		--menu ":::" 30 35 30 $genuri  2> $tempfile
      		selectie0=$?
		abandon
		nume_gen=`cat $tempfile`
		nr_gen=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_genuri|sed -n "/$nume_gen/="`
		gen=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_genuri|awk '{print $2}'|sed 's/_/ /g'|sed -n "${nr_gen}p"`
		gen1=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_genuri|awk '{print $1}'|sed -n "${nr_gen}p"`
		wget -qO - "$gen"|grep yp.shoutcast|sed '/icon-play/d'|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $8,$7}' >$HOME/.tvmaxe-cli/.tmp/shoutcast_radio

			lista_radio=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_radio|awk '{print $1,"|"}'|sed 's/\&amp;/\&/g'`

			$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Shoutcast-radio" --clear \
         		--menu ":::" 30 35 30 $lista_radio  2> $tempfile
      			selectie0=$?
			abandon
			nume_radio=`cat $tempfile`
			nr_radio=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_radio|sed -n "/$nume_radio/="`

			radio=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_radio|awk '{print $2}'|sed -n "${nr_radio}p"`
			echo $nume_radio $radio > $HOME/.tvmaxe-cli/.tmp/adr
			
;;
02)
		$DIALOG --title "Shoutcast" \
			--backtitle "tvmaxe-cli" \
			--inputbox "Ce post de radio cautati?" 8 50  2>$tempfile
			selectie0=$?
			abandon
			radio_cautat=`cat $tempfile`

		wget -qO - "http://www.shoutcast.com/radiolist.cfm?action=search&string="$radio_cautat""|grep yp.shoutcast|sed '/icon-play/d'|sed 's/ /_/g;s/[<>"]/ /g'|awk '{print $8,$7}'>$HOME/.tvmaxe-cli/.tmp/radio_cautat

if [[ -z `cat $HOME/.tvmaxe-cli/.tmp/radio_cautat` ]];then
	$DIALOG	--title 'Eroare' \
	--infobox '\n Nu am gasit postul radio' 5 50;sleep 2
	exit 0
else
		radio_gasite=`cat $HOME/.tvmaxe-cli/.tmp/radio_cautat|awk '{print $1,"|"}'|sed 's/\&amp;/\&/g'`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Shoutcast-radio" --clear \
         		--menu ":::" 30 40 30 $radio_gasite  2> $tempfile
      			selectie0=$?
			abandon
			nume_radio_gasit=`cat $tempfile`
			nr_radio_gasit=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_cautat|sed -n "/$nume_radio_gasit/="`
			radio=`cat $HOME/.tvmaxe-cli/.tmp/shoutcast_radio|awk '{print $2}'|sed -n "${nr_radio}p"`
			echo $nume_radio_gasit $radio_gasit > $HOME/.tvmaxe-cli/.tmp/adr
			
fi
;;
esac
./filtrutv
