#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
$DIALOG --infobox "Procesez baza de date streams.magazinmixt" 3 50

 	
wget -qO - http://streams.magazinmixt.ro/ro/streams.json|sed 's/name/\nname/g;s/ /_/g;s/","/ /g;s/,"/ /g'|grep protocol > $HOME/.tvmaxe-cli/.tmp/liste_stream


streams_magazin=`cat $HOME/.tvmaxe-cli/.tmp/liste_stream|sed -e 's/^.*\(name[^ ,]*\).*$/\1/'|sed 's/name":"//g'|nl`
#awk '{ print $0, NR }'

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Streams-magazinmixt |" --clear \
          --menu ":::" 30 35 30 $streams_magazin 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi

		nr_post_tv=`cat $tempfile`
		nume_tv=`cat $HOME/.tvmaxe-cli/.tmp/liste_stream|sed -e 's/^.*\(name[^ ,]*\).*$/\1/'|sed 's/name":"//g'|sed '1d'|sed -n "${nr_post_tv}p"`
		adresa_tv=`cat $HOME/.tvmaxe-cli/.tmp/liste_stream|sed -e 's/^.*\(address[^ ,]*\).*$/\1/'|sed 's/address":"//g'|sed '1d'|sed -n "${nr_post_tv}p"`
 		echo $nume_tv $adresa_tv> $HOME/.tvmaxe-cli/.tmp/adr
./filtrutv
