#! /bin/bash
$DIALOG --infobox "Procesez baza de date streams.magazinmixt" 3 50

 	wget -qO - http://streams.magazinmixt.ro/modules/channels/channels_store.php|sed 's/ /|/g;s/","/ /g;s/name/\nname/g;s/\\//g'|awk '{print $1,$3}'|sed 's/name":"//g;s/addr":"//g'|sed '1d'|sed 's/swfUrl/\-\-swfUrl/;s/pageUrl/\-\-pageUrl/;s/playpath/\-\-playpath/;s/token/\-\-token/;s/live=1/\-\-live/'> $HOME/.tvmaxe-cli/.tmp/liste_stream

streams_magazin=`cat $HOME/.tvmaxe-cli/.tmp/liste_stream|awk '{print $1}'|sed 's/|/_/g'|nl`


$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Streams-magazinmixt |" --clear \
          --menu ":::" 30 35 30 $streams_magazin 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi

		nr_post_tv=`cat $tempfile`
 		cat $HOME/.tvmaxe-cli/.tmp/liste_stream|awk '{print $1,$2}'|sed -n "${nr_post_tv}p"> $HOME/.tvmaxe-cli/.tmp/adr
./filtrutv
