#!/bin/bash -x

source config

wget -qO - https://www.copy.com/s/TuQgVuEzosvC/teatru%20radiofonic|grep mp3|sed 's/"url":"/\n/g;s/"/ /g;s/\\//g'|awk '{print $1}'|sed '1d;$d'|sed 's/.mp3//g;s/\// /g;s/\%20/_/g'|awk '{print $NF}'>/tmp/tvmaxe-cli/teatrul_nume_piese
nume_piese=`cat /tmp/tvmaxe-cli/teatrul_nume_piese|awk '{print $1,"|"}'`

wget -qO - https://www.copy.com/s/TuQgVuEzosvC/teatru%20radiofonic|grep mp3|sed 's/"url":"/\n/g;s/"/ /g;s/\\//g;s/https/http/g'|awk '{print $1}'|sed 's/\%20/ /g'|sed '1d;$d'>/tmp/tvmaxe-cli/teatrul_adrese_piese
adrese=`cat /tmp/tvmaxe-cli/teatrul_adrese_piese`


$DIALOG --backtitle "tvmaxe-cli" \
		--title "| -Teatrul Radiofonic- |" --clear \
          	--menu ":::" 30 35 30  $nume_piese 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nume_piesa=`cat $tempfile`
nr_piesa=`cat /tmp/tvmaxe-cli/teatrul_nume_piese|sed -n "/$nume_piesa/="`
adr=`cat /tmp/tvmaxe-cli/teatrul_adrese_piese|sed -n "${nr_piesa}p"|sed 's/ /|/g'` 
echo "$nume_piesa $adr" > /tmp/tvmaxe-cli/adr
./filtrutv