#! /bin/bash -x

#http://fs99.trilulilu.ro/stream.php?type=audio&source=site&hash=c5742655e5ac8d&username=petreradu1&key=&sig=OZXrnTlJm7rmWUuqKCVMOQ&exp=1372539798
					

wget -qO - $1|grep swfobject|sed 's/[{,]/\n/g' > /tmp/trilu
ora=`date '+%R'`
exp=`date -d "$ora" +%s`
server=`cat /tmp/trilu|grep server|sed 's/"/ /g'|awk '{print $NF}'`
hash=`cat /tmp/trilu|grep hash|sed 's/"/ /g'|awk '{print $NF}'`
username=`cat /tmp/trilu|grep userid|sed 's/"/ /g'|awk '{print $NF}'`
key=`cat /tmp/trilu|grep key|sed 's/"/ /g'|awk '{print $NF}'`

echo "http://fs$server.trilulilu.ro/stream.php?type=audio&source=site&hash=$hash&username=$username&key=$key&exp=$exp"
