#! /bin/bash

if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
  source config
fi
lista_tv_regiune=`ls $HOME/.tvmaxe-cli/playlist|awk '{print $1,NR}'`

$DIALOG --backtitle "tvmaxe-cli" \
    --title "| -TV- |" --clear \
    --menu ":::" 30 35 30 $lista_tv_regiune 2> $tempfile
        selectie0=$?
  if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
      exit 0
  fi
regiune=`cat $tempfile`

liste_tv=`ls -A $HOME/.tvmaxe-cli/playlist/$regiune|sed 's/\./ /g'|awk '{print $1,NR}'`

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| -TV- |" --clear \
    --menu ":::" 30 35 30 $liste_tv 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
nume_lista_tv=`cat $tempfile`

#listatvro=`cat $HOME/.tvmaxe-cli/playlist/.$nume_lista_tv.tvro|awk '{print $1,"|"}'`
listatvro=`cat $HOME/.tvmaxe-cli/playlist/$regiune/.$nume_lista_tv.*|awk '{print $1"--"NR,"|"}'`

$DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Lista |" --clear \
          --menu ":::" 30 35 30 $listatvro 2> $tempfile
      	selectie0=$?
	if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   		exit 0
 	fi
  
nume_post_tv=`cat $tempfile`
#nr_post_tv=`cat $tempfile`
#nr_post_tv=`cat $HOME/.tvmaxe-cli/playlist/.$nume_lista_tv.tvro|sed -n "/$nume_post_tv/="`
nr_post_tv=`echo $nume_post_tv|sed 's/--/ /g'|awk '{print $2}'`
cat $HOME/.tvmaxe-cli/playlist/$regiune/.$nume_lista_tv.*|sed -n "${nr_post_tv}p" > $HOME/.tvmaxe-cli/.tmp/adr
adresa_tv=`cat $HOME/.tvmaxe-cli/.tmp/adr|awk '{print $2}'`
$DIALOG --infobox " Nume TV: $nume_post_tv \n Adresa: $adresa_tv" 6 50

    sleep 1

./filtrutv