#! /bin/bash -x
source config


Romania (){
$DIALOG --infobox "Actualizez liste.. \n Romania" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Romaniatv.tvro >  $HOME/.tvmaxe-cli/playlist/.Romaniatv.tvro
}

International () {
$DIALOG --infobox "Actualizez liste.. \n International" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.International.tvro > $HOME/.tvmaxe-cli/playlist/.International.tvro
}

Basarabia () {
$DIALOG --infobox "Actualizez liste.. \n Basarabia" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Basarabiatv.tvro > $HOME/.tvmaxe-cli/playlist/.Basarabiatv.tvro
}

Brazil () {
$DIALOG --infobox "Actualizez liste.. \n Brazil" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Brazil.tvro > $HOME/.tvmaxe-cli/playlist/.Brazil.tvro
}

Bulgaria () {
$DIALOG --infobox "Actualizez liste.. \n Bulgaria" 6 25
wget -qO https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Bulgaria.tvro > $HOME/.tvmaxe-cli/playlist/.Bulgaria.tvro
}

China () {
$DIALOG --infobox "Actualizez liste.. \n China" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.China.tvro > $HOME/.tvmaxe-cli/playlist/.China.tvro
}

Denmark () {
$DIALOG --infobox "Actualizez liste.. \n Denmark" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Denmark.tvro >$HOME/.tvmaxe-cli/playlist/.Denmark.tvro
}

Finland () {
$DIALOG --infobox "Actualizez liste.. \n Finland" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Finland.tvro > $HOME/.tvmaxe-cli/playlist/.Finland.tvro
}

France () {
$DIALOG --infobox "Actualizez liste.. \n France" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.France.tvro > $HOME/.tvmaxe-cli/playlist/.France.tvro
}

Germany () {
$DIALOG --infobox "Actualizez liste.. \n Germany" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Germany.tvro > $HOME/.tvmaxe-cli/playlist/.Germany.tvro
}

Greece () {
$DIALOG --infobox "Actualizez liste.. \n Greece" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Greece.tvro > $HOME/.tvmaxe-cli/playlist/.Greece.tvro
}

Hungary () {
$DIALOG --infobox "Actualizez liste.. \n Hungary" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Hungary.tvro > $HOME/.tvmaxe-cli/playlist/.Hungary.tvro
}

Italy () {
$DIALOG --infobox "Actualizez liste.. \n Italy" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Italy.tvro > $HOME.Italy.tvro/.tvmaxe-cli/playlist/.Italy.tvro
}

Moldova () {
$DIALOG --infobox "Actualizez liste.. \n Moldova" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Moldova.tvro > $HOME/.tvmaxe-cli/playlist/.Moldova.tvro
}

Music () {
$DIALOG --infobox "Actualizez liste.. \n Music" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Music.tvro > $HOME/.tvmaxe-cli/playlist/.Music.tvro
}

Norway () {
$DIALOG --infobox "Actualizez liste.. \n Norway" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Norway.tvro > $HOME/.tvmaxe-cli/playlist/.Norway.tvro
}

Russia () {
$DIALOG --infobox "Actualizez liste.. \n Russia" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Russia.tvro > $HOME/.tvmaxe-cli/playlist/.Russia.tvro
}

Spain () {
$DIALOG --infobox "Actualizez liste.. \n Spain" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Spain.tvro > $HOME/.tvmaxe-cli/playlist/.Spain.tvro
}

Sport () {
$DIALOG --infobox "Actualizez liste.. \n Sport" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.Sport.tvro > $HOME/.tvmaxe-cli/playlist/.Sport.tvro
}

UK () {
$DIALOG --infobox "Actualizez liste.. \n UK" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.UK.tvro > $HOME/.tvmaxe-cli/playlist/.UK.tvro
}

USA () {
$DIALOG --infobox "Actualizez liste.. \n USA" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.USA.tvro>$HOME/.tvmaxe-cli/playlist/.USA.tvro
}

xxx () {
$DIALOG --infobox "Actualizez liste.. \n XXX" 6 25
wget -qO - https://raw.github.com/calvarr/tvmaxe-cli/master/playlist/.XxX.tvro > $HOME/.tvmaxe-cli/playlist/.XxX.tvro
}

##############################################################
Basarabia
Brazil
Bulgaria
China
Denmark
Finland
France
Germany
Greece
Hungary
International
Italy
Moldova
Music
Norway
Romaniatv
Russia
Spain
Sport
UK
USA
xxx
##############################################################
exit 0

