#!/bin/bash
cd $HOME/'.'tvmaxe-cli
if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi

mkdir -p $HOME/.tvmaxe-cli/.tmp
touch $HOME/.tvmaxe-cli/.tmp/adr


if [[ "$1" != "" ]]; then
echo "tvmaxe-cli $1" > $HOME/.tvmaxe-cli/.tmp/adr
#echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format
./fadr_externa
fi


	
					

gui () {
test_tty=`echo $DISPLAY X|awk '{print $2}'`
if [[ "$test_tty" = "X" ]];then
  if   [ `builtin type -p xdialog` ];then DIALOG=xdialog
  elif [ `builtin type -p Xdialog` ];then DIALOG=Xdialog
  elif [ `builtin type -p gdialog` ];then DIALOG=gdialog
  elif [ `builtin type -p kdialog` ];then DIALOG=kdialog
  else
  DIALOG=dialog
  fi
else
  DIALOG=dialog
fi

}
nogui () {
DIALOG=dialog
}
export DIALOG
$interfata
$actualizare
#export DIALOG
tempfile=`tempfile 2>/dev/null` || tempfile=$HOME/.tvmaxe-cli/.tmp/capclitmp$$
export tempfile
trap "rm -f $tempfile" 0 1 2 5 15
trap "rm -rf $HOME/.tvmaxe-cli/.tmp" 0 1 2 5 15

until [ "$selectie0" == "1" ]; do

  $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Meniu |" --clear \
          --menu ":::" 25 30 25 \
	"01" "TV on-line" \
	"02" "Streams-magazinmixt" \
	"03" "Radio on-line" \
	"04" "Meteo" \
	"05" "Filme" \
	"06" "Youtube" \
	"07" "git_pull" 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`
  
  case "$selectat" in
	01) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./TV_online;;
	02) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./stream_magazin;;
	03) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./radio_online;;
	04) ./meteo ;;
	05) ./filme;;
	06) echo "Youtube" > $HOME/.tvmaxe-cli/.tmp/adr ; ./youtube;;
	07) ./gitpull;;
			
  esac

  if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   #killall ceas
	stty sane
   exit 0
  fi
done

