#!/bin/bash
cd $HOME/'.'tvmaxe-cli
source config
./ceas &
mkdir -p $HOME/.tvmaxe-cli/.tmp
touch $HOME/.tvmaxe-cli/.tmp/adr
if [ ! -f $HOME/.tvmaxe-cli/.commit_tv ]; then
	echo "Lipsa fisier $HOME/.tvmaxe-cli/.commit_tv"
	echo "creez $HOME/.tvmaxe-cli/.commit_tv"
    wget -qO - https://github.com/calvarr/tvmaxe-cli/commits/master|grep 'class="sha"'|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}' > $HOME/.tvmaxe-cli/.commit_tv
fi



auto_actualizare () {
	$DIALOG --infobox "Caut actualizari disponibile..." 5 20
	commit1=`wget -qO - https://github.com/calvarr/tvmaxe-cli/commits/master|grep 'class="sha"'|sed -n '1p'|sed 's/ /_/g;s/[><]/ /g'|awk '{print $3}'`
	commit2=`cat $HOME/.tvmaxe-cli/.commit_tv`

	if [[ "$commit1" != "$commit2" ]]
	then 
		
		./actualizare
	else
		$DIALOG --infobox "Nu au fost gasite actualizari \n $commit1=$commit2" 5 20
		sleep 2
	fi
					}

gui () {
test_tty=`echo $DISPLAY X|awk '{print $2}'`
if [[ "$test_tty" = "X" ]];then
  if   [ `builtin type -p xdialog` ];then DIALOG=xdialog
  elif [ `builtin type -p Xdialog` ];then DIALOG=Xdialog
  elif [ `builtin type -p gdialog` ];then DIALOG=gdialog
  elif [ `builtin type -p kdialog` ];then DIALOG=kdialog
  else
  DIALOG=dialog
  fi
else
  DIALOG=dialog
fi

}
nogui () {
DIALOG=dialog
}
export DIALOG
$interfata
$actualizare
#export DIALOG
tempfile=`tempfile 2>/dev/null` || tempfile=$HOME/.tvmaxe-cli/.tmp/capclitmp$$
export tempfile
trap "rm -f $tempfile" 0 1 2 5 15
trap "rm -rf $HOME/.tvmaxe-cli/.tmp" 0 1 2 5 15
if [[ "$1" != "" ]]; then
echo "tvmaxe-cli $1" > $HOME/.tvmaxe-cli/.tmp/adr
echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format
./adr_externa
fi
until [ "$selectie0" == "1" ]; do

  $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Meniu |" --clear \
          --menu ":::" 25 30 25 \
	"01" "TV on-line" \
	"02" "Streams-magazinmixt" \
	"03" "Evenimente TV" \
	"04" "Radio on-line" \
	"05" "Meteo" \
	"06" "Filme" \
	"07" "Youtube" \
	"08" "Divertisment" \
	"09" "Teatrul Radiofonic" \
	"10" "Favorite" \
	"11" "Captura web_tv" \
	"12" "Actualizare" \
	"13" "Parasiti" 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`
  
  case "$selectat" in
	01) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./TV_online;;
	02) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./stream_magazin;;
	03) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./evenimente;;
	04) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./radio_online;;
	05) ./meteo ;;
	06) ./filme;;
	07) echo "Youtube" > $HOME/.tvmaxe-cli/.tmp/adr ; ./youtube;;
	08) echo "Divertisment" > $HOME/.tvmaxe-cli/.tmp/adr ; ./divertisment;;
	09) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./teatrul_radiofonic;;
	10) ./favorite;;
	11) ./capstream;;
	12) ./actualizare;;
	13) killall ceas
		stty sane
		exit 0
			;;
  esac

  if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   killall ceas
	stty sane
   exit 0
  fi
done

