#!/bin/bash
cd $HOME/'.'tvmaxe-cli
mkdir -p $HOME/.tvmaxe-cli/.tmp
touch $HOME/.tvmaxe-cli/.tmp/adr
source config
./ceas &
gui () {
test_tty=`echo $DISPLAY X|awk '{print $2}'`
if [[ "$test_tty" = "X" ]];then
  if [ `builtin type -p xdialog` ];then DIALOG=xdialog
  elif [ `builtin type -p Xdialog` ];then DIALOG=Xdialog
  elif [ `builtin type -p gdialog` ];then DIALOG=gdialog
  elif [ `builtin type -p kdialog` ];then DIALOG=kdialog
  else
  DIALOG=dialog
  fi
else
  DIALOG=dialog
fi
}
nogui () {
DIALOG=dialog
}
$interfata
export DIALOG
tempfile=`tempfile 2>/dev/null` || tempfile=$HOME/.tvmaxe-cli/.tmp/capclitmp$$
export tempfile
trap "rm -f $tempfile" 0 1 2 5 15
trap "rm -rf $HOME/.tvmaxe-cli/.tmp" 0 1 2 5 15
if [[ "$1" != "" ]]; then
echo "tvmaxe-cli $1" > $HOME/.tvmaxe-cli/.tmp/adr
echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format
./adr_externa
fi

until [ "$selectie0" == "1" ]; do

  $DIALOG --backtitle "tvmaxe-cli" \
	  --title "| Meniu |" --clear \
          --menu ":::" 25 30 25 \
	"01" "TV on-line" \
	"02" "Radio on-line" \
	"03" "Shoutcast" \
	"04" "Filme" \
	"05" "Youtube" \
	"06" "Youtube Live" \
	"07" "Divertisment" \
	"08" "Teatrul Radiofonic" \
	"09" "Favorite" \
	"10" "Captura web_tv" \
	"11" "Configurare" \
	"12" "Actualizare" \
	"13" "Parasiti" 2>$tempfile
  selectie0=$?
  selectat=`cat $tempfile`
  
  case "$selectat" in
	01) echo $format_video tv > $HOME/.tvmaxe-cli/.tmp/format    ; ./TV_online;;
	02) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./radio_online;;
	03) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./shoutcast;;
	04) ./filme;;
	05) echo "Youtube" > $HOME/.tvmaxe-cli/.tmp/adr ; ./youtube;;
	06) ./youtube_tv;;
	07) echo "Divertisment" > $HOME/.tvmaxe-cli/.tmp/adr ; ./divertisment;;
	08) echo $format_audio radio > $HOME/.tvmaxe-cli/.tmp/format ; ./teatrul_radiofonic;;
	09) ./favorite;;
	10) ./capstream;;
	11) ./configurare;;
	12) ./actualizare;;
	13) killall ceas
		stty sane
		exit 0
			;;
  esac

  if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   killall ceas
	stty sane
   exit 0
  fi
done

