#! /bin/bash
source config
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   ./tvmaxe-cli
  fi
}

player1=echo "$player"|awk '{print $1}' &>/dev/null

		$DIALOG --title "| youtube |" \
			--backtitle "tvmaxe-cli" \
			--inputbox "Ce cautati?" 8 35  2>$tempfile
			selectie0=$?
			titlu=`cat $tempfile`
			abandon
pagini=`wget -qO -  http://www.youtube.com/results?search_query="$titlu"|grep data-page|wc -l`
> $HOME/.tvmaxe-cli/.tmp/yt
c=10
for a in `seq 1 $pagini` ; do
	
wget -qO - "http://www.youtube.com/results?search_query='$titlu'&page=$a"|grep yt-lockup-title >> $HOME/.tvmaxe-cli/.tmp/yt_temp

((c+=10));echo $c|$DIALOG --gauge "Caut.." 6 50 10
done

grep -i "watch?" $HOME/.tvmaxe-cli/.tmp/yt_temp |sed 's/ /_/g;s/"_/ /g;s/_"/ /g'|sed -e 's/^.*\(title=[^ ,]*\).*$/\1/'|sed 's/title="//g' > $HOME/.tvmaxe-cli/.tmp/title_yt

grep -i "watch?" $HOME/.tvmaxe-cli/.tmp/yt_temp |sed 's/ /_/g;s/"_/ /g;s/_"/ /g'|sed -e 's/^.*\(watch?[^ ,]*\).*$/\1/'|awk '{print "https://www.youtube.com/"$1}' > $HOME/.tvmaxe-cli/.tmp/adresa_yt

paste $HOME/.tvmaxe-cli/.tmp/title_yt $HOME/.tvmaxe-cli/.tmp/adresa_yt | column -s $'\t' -t > $HOME/.tvmaxe-cli/.tmp/yt


colectie=`cat $HOME/.tvmaxe-cli/.tmp/title_yt|awk '{print $1,"off"}'|nl`
nr_piese_lista=`cat $HOME/.tvmaxe-cli/.tmp/title_yt|wc -l`


youtube () {
adr_yt=`cat $HOME/.tvmaxe-cli/.tmp/yt|awk '{print $2}'|sed -n "${nr_linie_colectie}p"`
nume=`cat $HOME/.tvmaxe-cli/.tmp/yt|sed 's/%_/_/g;s/\&lt;b&gt;//g;s/\#39//g;s/&amp//'|awk '{print $1}'|sed -n "${nr_linie_colectie}p"`
}

youtube_rpi () {
	
	youtube-dl -g $adr_yt 2>/dev/null > $HOME/.tvmaxe-cli/.tmp/adr_yt
	adr_yt1=`cat $HOME/.tvmaxe-cli/.tmp/adr_yt`
	$player "$adr_yt1" &>/dev/null
}

youtube_pc () {
   			youtube-dl $adr_yt -o - 2>/dev/null|$player - &>/dev/null
   		}

$DIALOG --backtitle "tvmaxe-cli" \
          	--checklist ":::" 80 80 80 $colectie 2> $tempfile
      	selectie0=$?
	abandon
nr_linie=`cat $tempfile|sed 's/"//g'`

$DIALOG --backtitle "tvmaxe-cli" \
	 	--title "| Youtube |" --clear \
          	--menu ":::" 25 35 25 \
	"01" "Reda selectia" \
	"02" "Adauga la favorite*" \
	"03" "Descarca selectia" \
	"04" "Reda toate" \
	"05" "Deascarca toate" \
	"06" "Reda selectia audio" \
	"07" "Reda toate audio" \
	"08" "Conversie selectie wav" \
	"09" "Conversie selectie mp3" \
	"10" "Reveniti" 2>$tempfile
	selectie0=$?
	abandon
 	selectat=`cat $tempfile`
  
 
  case "$selectat" in

	01) ./abandon &
		
		for nr_linie_colectie in  $nr_linie ; do

	 youtube
	
 	 $youtube2

		done
		#killall $player1
	#exit 0
;;

	02)
	$DIALOG --backtitle "tvmaxe-cli" \
		--title "Creati o lista sau adaugati piesa la o lista existenta: " \
		--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
	selectie0=$?
	abandon
	selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
	for nr_linie_colectie in  $nr_linie ; do

	youtube
			echo "$nume $adr_yt" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
	done
		fi
		
;;

	03)
	for nr_linie_colectie in  $nr_linie ; do

	youtube
		
	youtube-dl $adr_yt -o $salvare/$nume.flv

	done

	exit 0
;;
	04)
		./abandon &
		for nr_linie_colectie in `seq 1 $nr_piese_lista` ; do
		
		youtube
		
   		$youtube2
   			
		done
		exit 0
;;
	05)
		
		for nr_linie_colectie in `seq 1 $nr_piese_lista` ; do
		youtube
		youtube-dl $adr_yt -o $salvare/$nume.flv 2>/dev/null
		done
		exit 0
;;
	06)
	./abandon &
	for nr_linie_colectie in  $nr_linie ; do

	youtube
		
	youtube-dl $adr_yt -o - 2>/dev/null|$player -novideo - &>/dev/null
done
exit 0
;;
#$($procesare -y -i "$gp3_yt" -acodec copy -vcodec copy -r 20 -f 3gp - 2>/dev/null|$player - &>/dev/null);stty sane
#$($procesare -y -i "$adr" -acodec libmp3lame -ar 44100 -vcodec copy -f flv - 2>/dev/null|$player - &>/dev/null);stty sane
	
#ffmpeg -f lavfi -i testsrc -filter_complex "split=4[a][b][c][d];[a]pad=iw*4:ih[w];[b]lutyuv=u=128:v=128[x];[c]lutyuv=y=0:v=128[y];[d]lutyuv=y=0:u=128[z];[w][x]overlay=w:0[wx];[wx][y]overlay=w*2:0[wxy];[wxy][z]overlay=w*3:0" -f nut - | ffplay -

#ffplay -f lavfi "amovie=$adr,asplit=3[out1][a][b]; [a]showwaves=s=640x240,pad=iw:ih*2[waves]; [b]showspectrum=s=640x240[spectrum]; [waves][spectrum] overlay=0:h [out0]"

	07)./abandon &
	for nr_linie_colectie in `seq 1 $nr_piese_lista` ; do

		youtube
		
		youtube-dl $adr_yt -o - 2>/dev/null|$player -novideo - &>/dev/null

	done
	exit 0
;;

	08)
	for nr_linie_colectie in  $nr_linie ; do

	youtube
		
	youtube-dl $adr_yt -o - 2>/dev/null|$procesare -i "-" -vn -acodec pcm_s16le -ar 16000 -ac 1 -f wav $salvare/$nume.wav
	#youtube-dl  --extract-audio  --audio-format wav  --audio-quality 0 $adr_yt -o $salvare/$nume.wav
	done
	exit 0
;;
	09)
	for nr_linie_colectie in  $nr_linie ; do

	youtube
		
	youtube-dl $adr_yt -o - 2>/dev/null|$procesare -i "-" -acodec libmp3lame -ac 2 -ab 128 -vn -y $salvare/$nume.mp3

	done
	exit 0
;;
	10) exit 0;;
esac

############################################

