#! /bin/bash


if [ -f /$HOME/.config_tvmaxe-cli ]
then
    source $HOME/.config_tvmaxe-cli
else
	source config
fi
######################################
ext=.flv
abandon () {
if [ "$selectie0" == "255" ]||[ "$selectie0" == "1" ]; then
   
exit 0
  fi
}

despre_film () {
$DIALOG --infobox "Procesez..." 5 15
$DIALOG --infobox "$descriere" 30 50 ; sleep 5
}

meniufilm () {
	
$DIALOG --backtitle "tvmaxe-cli" \
	  --title "$nume" --clear \
          --menu "::: " 30 35 30 \
	"01" "Redati" \
	"02" "Inregistrati" \
	"03" "Descarcati" \
	"04" "Adaugati la favorite" \
	"05" "Parasiti" 2>$tempfile
  selectie0=$?
	abandon
  selectat=`cat $tempfile`

  case "$selectat" in
	01)	 
$DIALOG --infobox "$nume1" 5 30
		$player $film1  &>/dev/null
		$postplay
		#exit 0
;;

	02)	wget -O $salvare/$nume1$ext $film1 &>/dev/null &
		sleep $delay ; 
		$player $salvare/$nume1$ext $postplay  &>/dev/null
		killall wget 
		exit 0
;;

	03)	axel -o $salvare/$nume1$ext $film1 2>&1 |grep "%]"| sed -u -e "s,\.,,g;s/\]//" | awk '{printf("\b\b\b\b%4s", $2)}' 2>&1
			echo -ne "\b\b\b\b" #|$DIALOG --gauge "Descarc.." 6 50 10
		exit 0
;;

	04)	
			$DIALOG --backtitle "tvmaxe-cli" \
				--title "Creati o lista sau adaugati postul la o lista existenta: " \
				--inputbox "Liste existente: \n $liste" 15 75 2>$tempfile
		selectie0=$?
		abandon
		selectat1=`cat $tempfile`
		if [[ "$selectat1" = "" ]];then
			$DIALOG --title "Eroare" \
				--msgbox "\n Introduceti numele listei" 6 50
		else
			echo "$nume1 $film1" >> $HOME/'.'tvmaxe-cli/playlist/$selectat1.tv
		fi
		if [ "$selectie0" == "255" ]; then
   			exit 0
  		fi ;;


	05)	exit 0 ;;
  esac

 }

	$DIALOG --backtitle "tvmaxe-cli" \
	  --title "Filme zfilmeonline.org" --clear \
          --menu ":::" 25 30 25 \
	"01" "Filme noi" \
	"02" "Dupa gen" \
	"03" "Parasiti"  2>$tempfile
  selectie0=$?
abandon
  selectat=`cat $tempfile`
case "$selectat" in


	01) 
	$DIALOG --infobox "Procesez..." 5 15
wget -qO - http://www.zfilmeonline.org/|grep movief|sed 's/ /_/g;s/["<>]/ /g'|awk '{print $5,$4}'|sed '/^\s*$/d' > $HOME/.tvmaxe-cli/.tmp/zfilme_noi
filmenoi=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_noi|awk '{print $1,"|"}'`

		$DIALOG --backtitle "tvmaxe-cli" \
		  --title "Noi aparitii" --clear \
         	 --menu ":::" 30 50 30 $filmenoi  2> $tempfile
      		selectie0=$?
		abandon
		$DIALOG --infobox "Procesez..." 5 15
		nume_film_nou=`cat $tempfile`
		nr_film_nou=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_noi|sed -n "/$nume_film_nou/="`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_noi|awk '{print $2}'|sed -n "${nr_film_nou}p"`

		server1=`wget -qO - $adresa|grep mail.ru|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
		film1=`wget -qO - $server1|grep videoSrc|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_noi|awk '{print $1}'|sed 's/_/ /g'|sed -n "${nr_film_nou}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		meniufilm
;;
02) 
		$DIALOG --infobox "Procesez..." 5 15
		wget -qO - http://www.zfilmeonline.org/|grep "/category/"|sed 's/ /_/g;s/["<>]/ /g'|awk '{print $7,$4}'|sed '1d' > $HOME/.tvmaxe-cli/.tmp/zfilme_categorii

			
			gen_film=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_categorii|awk '{print $1}'|nl`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "Ordonare dupa gen" --clear \
         	 	--menu ":::" 30 35 30 $gen_film 2> $tempfile
      		selectie0=$?
		abandon
		nr_film_gen=`cat $tempfile`
		genul=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_categorii|awk '{print $2}'|sed -n "${nr_film_gen}p"`
		nume_gen=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_categorii|awk '{print $1}'|sed -n "${nr_film_gen}p"`

		pagini_gen=`wget -qO - http://www.zfilmeonline.org/category/filme-online/fantezie/|grep "'pages'"|sed 's/ /_/g;s/[<>]/ /g'|awk '{print $2}'|sed 's/_/ /g'|awk '{print $NF}'`
		cumulpg=`echo $genul"page/"`
		i=1

		for p in `seq 1 $pagini_gen` ; do
			wget -qO - $cumulpg$(( i++ ))|grep movief|sed 's/ /_/g;s/["<>]/ /g'|awk '{print $5,$4}'|sed '/^\s*$/d' >>$HOME/.tvmaxe-cli/.tmp/zfilme_gen
		$DIALOG --infobox "Pagini $(( i++ ))" 5 15;sleep 0.5
		done

		filme_gen=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_gen|awk '{print $1}'|nl`
		$DIALOG --backtitle "tvmaxe-cli" \
		  	--title "$nume_gen" --clear \
         	 	--menu ":::" 30 70 30 $filme_gen 2> $tempfile
      		selectie0=$?
		abandon
		nr_film_gen1=`cat $tempfile`
		adresa=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_gen|awk '{print $2}'|sed -n "${nr_film_gen1}p"`
		
		server1=`wget -qO - $adresa|grep mail.ru|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
		film1=`wget -qO - $server1|grep videoSrc|sed 's/ /_/g;s/"/ /g'|awk '{print $2}'`
		nume=`cat $HOME/.tvmaxe-cli/.tmp/zfilme_gen|awk '{print $1}'|sed 's/_/ /g'|sed -n "${nr_film_gen1}p"`
		nume1=`echo $nume|sed 's/ /_/g'`
		meniufilm
 ;;
03) exit 0
 ;;
esac

exit 0